// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/product_service/product/product_image/v1/product_image.proto

package product_imagev1

import (
	v1 "github.com/mikhail5545/product-service-client/pb/proto/product_service/image/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUuid     []byte                 `protobuf:"bytes,1,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
	ProductUuid   []byte                 `protobuf:"bytes,2,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Position      uint32                 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	IsMain        bool                   `protobuf:"varint,4,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	VariantUuid   []byte                 `protobuf:"bytes,5,opt,name=variant_uuid,json=variantUuid,proto3,oneof" json:"variant_uuid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     []byte                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	CreatedByName *string                `protobuf:"bytes,8,opt,name=created_by_name,json=createdByName,proto3,oneof" json:"created_by_name,omitempty"`
	Note          *string                `protobuf:"bytes,9,opt,name=note,proto3,oneof" json:"note,omitempty"`
	Image         *v1.Image              `protobuf:"bytes,10,opt,name=image,proto3,oneof" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{0}
}

func (x *ProductImage) GetImageUuid() []byte {
	if x != nil {
		return x.ImageUuid
	}
	return nil
}

func (x *ProductImage) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *ProductImage) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ProductImage) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

func (x *ProductImage) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *ProductImage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductImage) GetCreatedBy() []byte {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *ProductImage) GetCreatedByName() string {
	if x != nil && x.CreatedByName != nil {
		return *x.CreatedByName
	}
	return ""
}

func (x *ProductImage) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *ProductImage) GetImage() *v1.Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type AssociateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid      []byte                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	MediaServiceUuid []byte                 `protobuf:"bytes,2,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	Position         uint32                 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	IsMain           bool                   `protobuf:"varint,4,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	VariantUuid      []byte                 `protobuf:"bytes,5,opt,name=variant_uuid,json=variantUuid,proto3,oneof" json:"variant_uuid,omitempty"`
	Note             string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	AdminUuid        []byte                 `protobuf:"bytes,7,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName        string                 `protobuf:"bytes,8,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssociateRequest) Reset() {
	*x = AssociateRequest{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateRequest) ProtoMessage() {}

func (x *AssociateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateRequest.ProtoReflect.Descriptor instead.
func (*AssociateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{1}
}

func (x *AssociateRequest) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *AssociateRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

func (x *AssociateRequest) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AssociateRequest) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

func (x *AssociateRequest) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *AssociateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AssociateRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *AssociateRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type AssociateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociateResponse) Reset() {
	*x = AssociateResponse{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateResponse) ProtoMessage() {}

func (x *AssociateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateResponse.ProtoReflect.Descriptor instead.
func (*AssociateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{2}
}

type SetMainRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid      []byte                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	MediaServiceUuid []byte                 `protobuf:"bytes,2,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetMainRequest) Reset() {
	*x = SetMainRequest{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMainRequest) ProtoMessage() {}

func (x *SetMainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMainRequest.ProtoReflect.Descriptor instead.
func (*SetMainRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{3}
}

func (x *SetMainRequest) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *SetMainRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

type SetMainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMainResponse) Reset() {
	*x = SetMainResponse{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMainResponse) ProtoMessage() {}

func (x *SetMainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMainResponse.ProtoReflect.Descriptor instead.
func (*SetMainResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{4}
}

type DisassociateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid      []byte                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	MediaServiceUuid []byte                 `protobuf:"bytes,2,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DisassociateRequest) Reset() {
	*x = DisassociateRequest{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisassociateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisassociateRequest) ProtoMessage() {}

func (x *DisassociateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisassociateRequest.ProtoReflect.Descriptor instead.
func (*DisassociateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{5}
}

func (x *DisassociateRequest) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *DisassociateRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

type DisassociateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisassociateResponse) Reset() {
	*x = DisassociateResponse{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisassociateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisassociateResponse) ProtoMessage() {}

func (x *DisassociateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisassociateResponse.ProtoReflect.Descriptor instead.
func (*DisassociateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{6}
}

type DeleteAllAssociationsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaServiceUuid []byte                 `protobuf:"bytes,1,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteAllAssociationsRequest) Reset() {
	*x = DeleteAllAssociationsRequest{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllAssociationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllAssociationsRequest) ProtoMessage() {}

func (x *DeleteAllAssociationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllAssociationsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllAssociationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAllAssociationsRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

type DeleteAllAssociationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllAssociationsResponse) Reset() {
	*x = DeleteAllAssociationsResponse{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllAssociationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllAssociationsResponse) ProtoMessage() {}

func (x *DeleteAllAssociationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllAssociationsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAllAssociationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{8}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_product_service_product_product_image_v1_product_image_proto protoreflect.FileDescriptor

const file_proto_product_service_product_product_image_v1_product_image_proto_rawDesc = "" +
	"\n" +
	"Bproto/product_service/product/product_image/v1/product_image.proto\x12.proto.product_service.product.product_image.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*proto/product_service/image/v1/image.proto\"\xdb\x03\n" +
	"\fProductImage\x12\x1d\n" +
	"\n" +
	"image_uuid\x18\x01 \x01(\fR\timageUuid\x12!\n" +
	"\fproduct_uuid\x18\x02 \x01(\fR\vproductUuid\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\rR\bposition\x12\x17\n" +
	"\ais_main\x18\x04 \x01(\bR\x06isMain\x12&\n" +
	"\fvariant_uuid\x18\x05 \x01(\fH\x00R\vvariantUuid\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\"\n" +
	"\n" +
	"created_by\x18\a \x01(\fH\x01R\tcreatedBy\x88\x01\x01\x12+\n" +
	"\x0fcreated_by_name\x18\b \x01(\tH\x02R\rcreatedByName\x88\x01\x01\x12\x17\n" +
	"\x04note\x18\t \x01(\tH\x03R\x04note\x88\x01\x01\x12@\n" +
	"\x05image\x18\n" +
	" \x01(\v2%.proto.product_service.image.v1.ImageH\x04R\x05image\x88\x01\x01B\x0f\n" +
	"\r_variant_uuidB\r\n" +
	"\v_created_byB\x12\n" +
	"\x10_created_by_nameB\a\n" +
	"\x05_noteB\b\n" +
	"\x06_image\"\xa3\x02\n" +
	"\x10AssociateRequest\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\fR\vproductUuid\x12,\n" +
	"\x12media_service_uuid\x18\x02 \x01(\fR\x10mediaServiceUuid\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\rR\bposition\x12\x17\n" +
	"\ais_main\x18\x04 \x01(\bR\x06isMain\x12&\n" +
	"\fvariant_uuid\x18\x05 \x01(\fH\x00R\vvariantUuid\x88\x01\x01\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\a \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\b \x01(\tR\tadminNameB\x0f\n" +
	"\r_variant_uuid\"\x13\n" +
	"\x11AssociateResponse\"a\n" +
	"\x0eSetMainRequest\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\fR\vproductUuid\x12,\n" +
	"\x12media_service_uuid\x18\x02 \x01(\fR\x10mediaServiceUuid\"\x11\n" +
	"\x0fSetMainResponse\"f\n" +
	"\x13DisassociateRequest\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\fR\vproductUuid\x12,\n" +
	"\x12media_service_uuid\x18\x02 \x01(\fR\x10mediaServiceUuid\"\x16\n" +
	"\x14DisassociateResponse\"L\n" +
	"\x1cDeleteAllAssociationsRequest\x12,\n" +
	"\x12media_service_uuid\x18\x01 \x01(\fR\x10mediaServiceUuid\"\x1f\n" +
	"\x1dDeleteAllAssociationsResponse\"\r\n" +
	"\vPingRequest\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2\x8c\x06\n" +
	"\x13ProductImageService\x12\x81\x01\n" +
	"\x04Ping\x12;.proto.product_service.product.product_image.v1.PingRequest\x1a<.proto.product_service.product.product_image.v1.PingResponse\x12\x90\x01\n" +
	"\tAssociate\x12@.proto.product_service.product.product_image.v1.AssociateRequest\x1aA.proto.product_service.product.product_image.v1.AssociateResponse\x12\x99\x01\n" +
	"\fDisassociate\x12C.proto.product_service.product.product_image.v1.DisassociateRequest\x1aD.proto.product_service.product.product_image.v1.DisassociateResponse\x12\x8a\x01\n" +
	"\aSetMain\x12>.proto.product_service.product.product_image.v1.SetMainRequest\x1a?.proto.product_service.product.product_image.v1.SetMainResponse\x12\xb4\x01\n" +
	"\x15DeleteAllAssociations\x12L.proto.product_service.product.product_image.v1.DeleteAllAssociationsRequest\x1aM.proto.product_service.product.product_image.v1.DeleteAllAssociationsResponseB\x8d\x03\n" +
	"2com.proto.product_service.product.product_image.v1B\x11ProductImageProtoP\x01Zogithub.com/mikhail5545/product-service-client/pb/proto/product_service/product/product_image/v1;product_imagev1\xa2\x02\x04PPPP\xaa\x02,Proto.ProductService.Product.ProductImage.V1\xca\x02,Proto\\ProductService\\Product\\ProductImage\\V1\xe2\x028Proto\\ProductService\\Product\\ProductImage\\V1\\GPBMetadata\xea\x020Proto::ProductService::Product::ProductImage::V1b\x06proto3"

var (
	file_proto_product_service_product_product_image_v1_product_image_proto_rawDescOnce sync.Once
	file_proto_product_service_product_product_image_v1_product_image_proto_rawDescData []byte
)

func file_proto_product_service_product_product_image_v1_product_image_proto_rawDescGZIP() []byte {
	file_proto_product_service_product_product_image_v1_product_image_proto_rawDescOnce.Do(func() {
		file_proto_product_service_product_product_image_v1_product_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_service_product_product_image_v1_product_image_proto_rawDesc), len(file_proto_product_service_product_product_image_v1_product_image_proto_rawDesc)))
	})
	return file_proto_product_service_product_product_image_v1_product_image_proto_rawDescData
}

var file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_product_service_product_product_image_v1_product_image_proto_goTypes = []any{
	(*ProductImage)(nil),                  // 0: proto.product_service.product.product_image.v1.ProductImage
	(*AssociateRequest)(nil),              // 1: proto.product_service.product.product_image.v1.AssociateRequest
	(*AssociateResponse)(nil),             // 2: proto.product_service.product.product_image.v1.AssociateResponse
	(*SetMainRequest)(nil),                // 3: proto.product_service.product.product_image.v1.SetMainRequest
	(*SetMainResponse)(nil),               // 4: proto.product_service.product.product_image.v1.SetMainResponse
	(*DisassociateRequest)(nil),           // 5: proto.product_service.product.product_image.v1.DisassociateRequest
	(*DisassociateResponse)(nil),          // 6: proto.product_service.product.product_image.v1.DisassociateResponse
	(*DeleteAllAssociationsRequest)(nil),  // 7: proto.product_service.product.product_image.v1.DeleteAllAssociationsRequest
	(*DeleteAllAssociationsResponse)(nil), // 8: proto.product_service.product.product_image.v1.DeleteAllAssociationsResponse
	(*PingRequest)(nil),                   // 9: proto.product_service.product.product_image.v1.PingRequest
	(*PingResponse)(nil),                  // 10: proto.product_service.product.product_image.v1.PingResponse
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
	(*v1.Image)(nil),                      // 12: proto.product_service.image.v1.Image
}
var file_proto_product_service_product_product_image_v1_product_image_proto_depIdxs = []int32{
	11, // 0: proto.product_service.product.product_image.v1.ProductImage.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: proto.product_service.product.product_image.v1.ProductImage.image:type_name -> proto.product_service.image.v1.Image
	9,  // 2: proto.product_service.product.product_image.v1.ProductImageService.Ping:input_type -> proto.product_service.product.product_image.v1.PingRequest
	1,  // 3: proto.product_service.product.product_image.v1.ProductImageService.Associate:input_type -> proto.product_service.product.product_image.v1.AssociateRequest
	5,  // 4: proto.product_service.product.product_image.v1.ProductImageService.Disassociate:input_type -> proto.product_service.product.product_image.v1.DisassociateRequest
	3,  // 5: proto.product_service.product.product_image.v1.ProductImageService.SetMain:input_type -> proto.product_service.product.product_image.v1.SetMainRequest
	7,  // 6: proto.product_service.product.product_image.v1.ProductImageService.DeleteAllAssociations:input_type -> proto.product_service.product.product_image.v1.DeleteAllAssociationsRequest
	10, // 7: proto.product_service.product.product_image.v1.ProductImageService.Ping:output_type -> proto.product_service.product.product_image.v1.PingResponse
	2,  // 8: proto.product_service.product.product_image.v1.ProductImageService.Associate:output_type -> proto.product_service.product.product_image.v1.AssociateResponse
	6,  // 9: proto.product_service.product.product_image.v1.ProductImageService.Disassociate:output_type -> proto.product_service.product.product_image.v1.DisassociateResponse
	4,  // 10: proto.product_service.product.product_image.v1.ProductImageService.SetMain:output_type -> proto.product_service.product.product_image.v1.SetMainResponse
	8,  // 11: proto.product_service.product.product_image.v1.ProductImageService.DeleteAllAssociations:output_type -> proto.product_service.product.product_image.v1.DeleteAllAssociationsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_service_product_product_image_v1_product_image_proto_init() }
func file_proto_product_service_product_product_image_v1_product_image_proto_init() {
	if File_proto_product_service_product_product_image_v1_product_image_proto != nil {
		return
	}
	file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_service_product_product_image_v1_product_image_proto_rawDesc), len(file_proto_product_service_product_product_image_v1_product_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_service_product_product_image_v1_product_image_proto_goTypes,
		DependencyIndexes: file_proto_product_service_product_product_image_v1_product_image_proto_depIdxs,
		MessageInfos:      file_proto_product_service_product_product_image_v1_product_image_proto_msgTypes,
	}.Build()
	File_proto_product_service_product_product_image_v1_product_image_proto = out.File
	file_proto_product_service_product_product_image_v1_product_image_proto_goTypes = nil
	file_proto_product_service_product_product_image_v1_product_image_proto_depIdxs = nil
}
