// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/product_service/training/v1/training.proto

package trainingv1

import (
	v1 "github.com/mikhail5545/product-service-client/pb/proto/product_service/product/v1"
	v11 "github.com/mikhail5545/product-service-client/pb/proto/product_service/variant/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug             *string                `protobuf:"bytes,2,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Subtitle         *string                `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	ShortDescription string                 `protobuf:"bytes,4,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	Tags             []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	AdminUuid        []byte                 `protobuf:"bytes,8,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName        string                 `protobuf:"bytes,9,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Note             string                 `protobuf:"bytes,10,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *CreateRequest) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *CreateRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *CreateRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *CreateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *v1.Product            `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetProduct() *v1.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title            *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Slug             *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	RegenerateSlug   bool                   `protobuf:"varint,4,opt,name=regenerate_slug,json=regenerateSlug,proto3" json:"regenerate_slug,omitempty"`
	Subtitle         *string                `protobuf:"bytes,5,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	Description      *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ShortDescription *string                `protobuf:"bytes,7,opt,name=short_description,json=shortDescription,proto3,oneof" json:"short_description,omitempty"`
	Tags             []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata         *string                `protobuf:"bytes,9,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	MetaTitle        *string                `protobuf:"bytes,10,opt,name=meta_title,json=metaTitle,proto3,oneof" json:"meta_title,omitempty"`
	MetaDescription  *string                `protobuf:"bytes,11,opt,name=meta_description,json=metaDescription,proto3,oneof" json:"meta_description,omitempty"`
	Updates          *fieldmaskpb.FieldMask `protobuf:"bytes,12,opt,name=updates,proto3,oneof" json:"updates,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateRequest) GetRegenerateSlug() bool {
	if x != nil {
		return x.RegenerateSlug
	}
	return false
}

func (x *UpdateRequest) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *UpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRequest) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *UpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateRequest) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *UpdateRequest) GetMetaTitle() string {
	if x != nil && x.MetaTitle != nil {
		return *x.MetaTitle
	}
	return ""
}

func (x *UpdateRequest) GetMetaDescription() string {
	if x != nil && x.MetaDescription != nil {
		return *x.MetaDescription
	}
	return ""
}

func (x *UpdateRequest) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title            *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Slug             *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Subtitle         *string                `protobuf:"bytes,4,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	Description      *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ShortDescription *string                `protobuf:"bytes,6,opt,name=short_description,json=shortDescription,proto3,oneof" json:"short_description,omitempty"`
	Tags             []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata         *string                `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	MetaTitle        *string                `protobuf:"bytes,9,opt,name=meta_title,json=metaTitle,proto3,oneof" json:"meta_title,omitempty"`
	MetaDescription  *string                `protobuf:"bytes,10,opt,name=meta_description,json=metaDescription,proto3,oneof" json:"meta_description,omitempty"`
	Updates          *fieldmaskpb.FieldMask `protobuf:"bytes,11,opt,name=updates,proto3,oneof" json:"updates,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateResponse) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateResponse) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateResponse) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *UpdateResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateResponse) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *UpdateResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateResponse) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *UpdateResponse) GetMetaTitle() string {
	if x != nil && x.MetaTitle != nil {
		return *x.MetaTitle
	}
	return ""
}

func (x *UpdateResponse) GetMetaDescription() string {
	if x != nil && x.MetaDescription != nil {
		return *x.MetaDescription
	}
	return ""
}

func (x *UpdateResponse) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type CreateVariantRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductUuid     []byte                 `protobuf:"bytes,1,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Sku             *string                `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Option1         *string                `protobuf:"bytes,4,opt,name=option1,proto3,oneof" json:"option1,omitempty"`
	Option2         *string                `protobuf:"bytes,5,opt,name=option2,proto3,oneof" json:"option2,omitempty"`
	Option3         *string                `protobuf:"bytes,6,opt,name=option3,proto3,oneof" json:"option3,omitempty"`
	DurationMinutes *int32                 `protobuf:"varint,7,opt,name=duration_minutes,json=durationMinutes,proto3,oneof" json:"duration_minutes,omitempty"`
	Format          v11.VariantFormat      `protobuf:"varint,8,opt,name=format,proto3,enum=proto.product_service.variant.v1.VariantFormat" json:"format,omitempty"`
	MaxSeats        *int32                 `protobuf:"varint,9,opt,name=max_seats,json=maxSeats,proto3,oneof" json:"max_seats,omitempty"`
	AdminUuid       []byte                 `protobuf:"bytes,10,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName       string                 `protobuf:"bytes,11,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Note            string                 `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateVariantRequest) Reset() {
	*x = CreateVariantRequest{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariantRequest) ProtoMessage() {}

func (x *CreateVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariantRequest.ProtoReflect.Descriptor instead.
func (*CreateVariantRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVariantRequest) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *CreateVariantRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVariantRequest) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *CreateVariantRequest) GetOption1() string {
	if x != nil && x.Option1 != nil {
		return *x.Option1
	}
	return ""
}

func (x *CreateVariantRequest) GetOption2() string {
	if x != nil && x.Option2 != nil {
		return *x.Option2
	}
	return ""
}

func (x *CreateVariantRequest) GetOption3() string {
	if x != nil && x.Option3 != nil {
		return *x.Option3
	}
	return ""
}

func (x *CreateVariantRequest) GetDurationMinutes() int32 {
	if x != nil && x.DurationMinutes != nil {
		return *x.DurationMinutes
	}
	return 0
}

func (x *CreateVariantRequest) GetFormat() v11.VariantFormat {
	if x != nil {
		return x.Format
	}
	return v11.VariantFormat(0)
}

func (x *CreateVariantRequest) GetMaxSeats() int32 {
	if x != nil && x.MaxSeats != nil {
		return *x.MaxSeats
	}
	return 0
}

func (x *CreateVariantRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *CreateVariantRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *CreateVariantRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateVariantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variant       *v11.Variant           `protobuf:"bytes,1,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVariantResponse) Reset() {
	*x = CreateVariantResponse{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariantResponse) ProtoMessage() {}

func (x *CreateVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariantResponse.ProtoReflect.Descriptor instead.
func (*CreateVariantResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVariantResponse) GetVariant() *v11.Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

type UpdateVariantRequest struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Uuid            []byte                      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ProductUuid     []byte                      `protobuf:"bytes,5,opt,name=product_uuid,json=productUuid,proto3" json:"product_uuid,omitempty"`
	Title           *string                     `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Sku             *string                     `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	RegenerateSku   bool                        `protobuf:"varint,4,opt,name=regenerate_sku,json=regenerateSku,proto3" json:"regenerate_sku,omitempty"`
	InventoryPolicy *v11.VariantInventoryPolicy `protobuf:"varint,6,opt,name=inventory_policy,json=inventoryPolicy,proto3,enum=proto.product_service.variant.v1.VariantInventoryPolicy,oneof" json:"inventory_policy,omitempty"`
	AllowBackorder  *bool                       `protobuf:"varint,7,opt,name=allow_backorder,json=allowBackorder,proto3,oneof" json:"allow_backorder,omitempty"`
	Option1         *string                     `protobuf:"bytes,8,opt,name=option1,proto3,oneof" json:"option1,omitempty"`
	Option2         *string                     `protobuf:"bytes,9,opt,name=option2,proto3,oneof" json:"option2,omitempty"`
	Option3         *string                     `protobuf:"bytes,10,opt,name=option3,proto3,oneof" json:"option3,omitempty"`
	DurationMinutes *int32                      `protobuf:"varint,11,opt,name=duration_minutes,json=durationMinutes,proto3,oneof" json:"duration_minutes,omitempty"`
	Format          *v11.VariantFormat          `protobuf:"varint,12,opt,name=format,proto3,enum=proto.product_service.variant.v1.VariantFormat,oneof" json:"format,omitempty"`
	MaxSeats        *int32                      `protobuf:"varint,13,opt,name=max_seats,json=maxSeats,proto3,oneof" json:"max_seats,omitempty"`
	Updates         *fieldmaskpb.FieldMask      `protobuf:"bytes,14,opt,name=updates,proto3,oneof" json:"updates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateVariantRequest) Reset() {
	*x = UpdateVariantRequest{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariantRequest) ProtoMessage() {}

func (x *UpdateVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariantRequest.ProtoReflect.Descriptor instead.
func (*UpdateVariantRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVariantRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateVariantRequest) GetProductUuid() []byte {
	if x != nil {
		return x.ProductUuid
	}
	return nil
}

func (x *UpdateVariantRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateVariantRequest) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *UpdateVariantRequest) GetRegenerateSku() bool {
	if x != nil {
		return x.RegenerateSku
	}
	return false
}

func (x *UpdateVariantRequest) GetInventoryPolicy() v11.VariantInventoryPolicy {
	if x != nil && x.InventoryPolicy != nil {
		return *x.InventoryPolicy
	}
	return v11.VariantInventoryPolicy(0)
}

func (x *UpdateVariantRequest) GetAllowBackorder() bool {
	if x != nil && x.AllowBackorder != nil {
		return *x.AllowBackorder
	}
	return false
}

func (x *UpdateVariantRequest) GetOption1() string {
	if x != nil && x.Option1 != nil {
		return *x.Option1
	}
	return ""
}

func (x *UpdateVariantRequest) GetOption2() string {
	if x != nil && x.Option2 != nil {
		return *x.Option2
	}
	return ""
}

func (x *UpdateVariantRequest) GetOption3() string {
	if x != nil && x.Option3 != nil {
		return *x.Option3
	}
	return ""
}

func (x *UpdateVariantRequest) GetDurationMinutes() int32 {
	if x != nil && x.DurationMinutes != nil {
		return *x.DurationMinutes
	}
	return 0
}

func (x *UpdateVariantRequest) GetFormat() v11.VariantFormat {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return v11.VariantFormat(0)
}

func (x *UpdateVariantRequest) GetMaxSeats() int32 {
	if x != nil && x.MaxSeats != nil {
		return *x.MaxSeats
	}
	return 0
}

func (x *UpdateVariantRequest) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateVariantResponse struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Uuid            []byte                      `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title           *string                     `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Sku             *string                     `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	InventoryPolicy *v11.VariantInventoryPolicy `protobuf:"varint,4,opt,name=inventory_policy,json=inventoryPolicy,proto3,enum=proto.product_service.variant.v1.VariantInventoryPolicy,oneof" json:"inventory_policy,omitempty"`
	AllowBackorder  *bool                       `protobuf:"varint,5,opt,name=allow_backorder,json=allowBackorder,proto3,oneof" json:"allow_backorder,omitempty"`
	Option1         *string                     `protobuf:"bytes,6,opt,name=option1,proto3,oneof" json:"option1,omitempty"`
	Option2         *string                     `protobuf:"bytes,7,opt,name=option2,proto3,oneof" json:"option2,omitempty"`
	Option3         *string                     `protobuf:"bytes,8,opt,name=option3,proto3,oneof" json:"option3,omitempty"`
	DurationMinutes *int32                      `protobuf:"varint,9,opt,name=duration_minutes,json=durationMinutes,proto3,oneof" json:"duration_minutes,omitempty"`
	Format          *v11.VariantFormat          `protobuf:"varint,10,opt,name=format,proto3,enum=proto.product_service.variant.v1.VariantFormat,oneof" json:"format,omitempty"`
	MaxSeats        *int32                      `protobuf:"varint,11,opt,name=max_seats,json=maxSeats,proto3,oneof" json:"max_seats,omitempty"`
	Updates         *fieldmaskpb.FieldMask      `protobuf:"bytes,12,opt,name=updates,proto3,oneof" json:"updates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateVariantResponse) Reset() {
	*x = UpdateVariantResponse{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariantResponse) ProtoMessage() {}

func (x *UpdateVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariantResponse.ProtoReflect.Descriptor instead.
func (*UpdateVariantResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVariantResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateVariantResponse) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateVariantResponse) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *UpdateVariantResponse) GetInventoryPolicy() v11.VariantInventoryPolicy {
	if x != nil && x.InventoryPolicy != nil {
		return *x.InventoryPolicy
	}
	return v11.VariantInventoryPolicy(0)
}

func (x *UpdateVariantResponse) GetAllowBackorder() bool {
	if x != nil && x.AllowBackorder != nil {
		return *x.AllowBackorder
	}
	return false
}

func (x *UpdateVariantResponse) GetOption1() string {
	if x != nil && x.Option1 != nil {
		return *x.Option1
	}
	return ""
}

func (x *UpdateVariantResponse) GetOption2() string {
	if x != nil && x.Option2 != nil {
		return *x.Option2
	}
	return ""
}

func (x *UpdateVariantResponse) GetOption3() string {
	if x != nil && x.Option3 != nil {
		return *x.Option3
	}
	return ""
}

func (x *UpdateVariantResponse) GetDurationMinutes() int32 {
	if x != nil && x.DurationMinutes != nil {
		return *x.DurationMinutes
	}
	return 0
}

func (x *UpdateVariantResponse) GetFormat() v11.VariantFormat {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return v11.VariantFormat(0)
}

func (x *UpdateVariantResponse) GetMaxSeats() int32 {
	if x != nil && x.MaxSeats != nil {
		return *x.MaxSeats
	}
	return 0
}

func (x *UpdateVariantResponse) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,2,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,3,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{8}
}

func (x *PublishRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *PublishRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *PublishRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *PublishRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{9}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{10}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_training_v1_training_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_training_v1_training_proto_rawDescGZIP(), []int{11}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_product_service_training_v1_training_proto protoreflect.FileDescriptor

const file_proto_product_service_training_v1_training_proto_rawDesc = "" +
	"\n" +
	"0proto/product_service/training/v1/training.proto\x12!proto.product_service.training.v1\x1a.proto/product_service/product/v1/product.proto\x1a.proto/product_service/variant/v1/variant.proto\x1a google/protobuf/field_mask.proto\"\x88\x02\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slug\x88\x01\x01\x12\x1f\n" +
	"\bsubtitle\x18\x03 \x01(\tH\x01R\bsubtitle\x88\x01\x01\x12+\n" +
	"\x11short_description\x18\x04 \x01(\tR\x10shortDescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\b \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\t \x01(\tR\tadminName\x12\x12\n" +
	"\x04note\x18\n" +
	" \x01(\tR\x04noteB\a\n" +
	"\x05_slugB\v\n" +
	"\t_subtitle\"U\n" +
	"\x0eCreateResponse\x12C\n" +
	"\aproduct\x18\x01 \x01(\v2).proto.product_service.product.v1.ProductR\aproduct\"\xc1\x04\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x01R\x04slug\x88\x01\x01\x12'\n" +
	"\x0fregenerate_slug\x18\x04 \x01(\bR\x0eregenerateSlug\x12\x1f\n" +
	"\bsubtitle\x18\x05 \x01(\tH\x02R\bsubtitle\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x03R\vdescription\x88\x01\x01\x120\n" +
	"\x11short_description\x18\a \x01(\tH\x04R\x10shortDescription\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1f\n" +
	"\bmetadata\x18\t \x01(\tH\x05R\bmetadata\x88\x01\x01\x12\"\n" +
	"\n" +
	"meta_title\x18\n" +
	" \x01(\tH\x06R\tmetaTitle\x88\x01\x01\x12.\n" +
	"\x10meta_description\x18\v \x01(\tH\aR\x0fmetaDescription\x88\x01\x01\x129\n" +
	"\aupdates\x18\f \x01(\v2\x1a.google.protobuf.FieldMaskH\bR\aupdates\x88\x01\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_slugB\v\n" +
	"\t_subtitleB\x0e\n" +
	"\f_descriptionB\x14\n" +
	"\x12_short_descriptionB\v\n" +
	"\t_metadataB\r\n" +
	"\v_meta_titleB\x13\n" +
	"\x11_meta_descriptionB\n" +
	"\n" +
	"\b_updates\"\x99\x04\n" +
	"\x0eUpdateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x01R\x04slug\x88\x01\x01\x12\x1f\n" +
	"\bsubtitle\x18\x04 \x01(\tH\x02R\bsubtitle\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x120\n" +
	"\x11short_description\x18\x06 \x01(\tH\x04R\x10shortDescription\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1f\n" +
	"\bmetadata\x18\b \x01(\tH\x05R\bmetadata\x88\x01\x01\x12\"\n" +
	"\n" +
	"meta_title\x18\t \x01(\tH\x06R\tmetaTitle\x88\x01\x01\x12.\n" +
	"\x10meta_description\x18\n" +
	" \x01(\tH\aR\x0fmetaDescription\x88\x01\x01\x129\n" +
	"\aupdates\x18\v \x01(\v2\x1a.google.protobuf.FieldMaskH\bR\aupdates\x88\x01\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_slugB\v\n" +
	"\t_subtitleB\x0e\n" +
	"\f_descriptionB\x14\n" +
	"\x12_short_descriptionB\v\n" +
	"\t_metadataB\r\n" +
	"\v_meta_titleB\x13\n" +
	"\x11_meta_descriptionB\n" +
	"\n" +
	"\b_updates\"\xff\x03\n" +
	"\x14CreateVariantRequest\x12!\n" +
	"\fproduct_uuid\x18\x01 \x01(\fR\vproductUuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x00R\x03sku\x88\x01\x01\x12\x1d\n" +
	"\aoption1\x18\x04 \x01(\tH\x01R\aoption1\x88\x01\x01\x12\x1d\n" +
	"\aoption2\x18\x05 \x01(\tH\x02R\aoption2\x88\x01\x01\x12\x1d\n" +
	"\aoption3\x18\x06 \x01(\tH\x03R\aoption3\x88\x01\x01\x12.\n" +
	"\x10duration_minutes\x18\a \x01(\x05H\x04R\x0fdurationMinutes\x88\x01\x01\x12G\n" +
	"\x06format\x18\b \x01(\x0e2/.proto.product_service.variant.v1.VariantFormatR\x06format\x12 \n" +
	"\tmax_seats\x18\t \x01(\x05H\x05R\bmaxSeats\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\n" +
	" \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\v \x01(\tR\tadminName\x12\x12\n" +
	"\x04note\x18\f \x01(\tR\x04noteB\x06\n" +
	"\x04_skuB\n" +
	"\n" +
	"\b_option1B\n" +
	"\n" +
	"\b_option2B\n" +
	"\n" +
	"\b_option3B\x13\n" +
	"\x11_duration_minutesB\f\n" +
	"\n" +
	"_max_seats\"\\\n" +
	"\x15CreateVariantResponse\x12C\n" +
	"\avariant\x18\x01 \x01(\v2).proto.product_service.variant.v1.VariantR\avariant\"\x8f\x06\n" +
	"\x14UpdateVariantRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12!\n" +
	"\fproduct_uuid\x18\x05 \x01(\fR\vproductUuid\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x01R\x03sku\x88\x01\x01\x12%\n" +
	"\x0eregenerate_sku\x18\x04 \x01(\bR\rregenerateSku\x12h\n" +
	"\x10inventory_policy\x18\x06 \x01(\x0e28.proto.product_service.variant.v1.VariantInventoryPolicyH\x02R\x0finventoryPolicy\x88\x01\x01\x12,\n" +
	"\x0fallow_backorder\x18\a \x01(\bH\x03R\x0eallowBackorder\x88\x01\x01\x12\x1d\n" +
	"\aoption1\x18\b \x01(\tH\x04R\aoption1\x88\x01\x01\x12\x1d\n" +
	"\aoption2\x18\t \x01(\tH\x05R\aoption2\x88\x01\x01\x12\x1d\n" +
	"\aoption3\x18\n" +
	" \x01(\tH\x06R\aoption3\x88\x01\x01\x12.\n" +
	"\x10duration_minutes\x18\v \x01(\x05H\aR\x0fdurationMinutes\x88\x01\x01\x12L\n" +
	"\x06format\x18\f \x01(\x0e2/.proto.product_service.variant.v1.VariantFormatH\bR\x06format\x88\x01\x01\x12 \n" +
	"\tmax_seats\x18\r \x01(\x05H\tR\bmaxSeats\x88\x01\x01\x129\n" +
	"\aupdates\x18\x0e \x01(\v2\x1a.google.protobuf.FieldMaskH\n" +
	"R\aupdates\x88\x01\x01B\b\n" +
	"\x06_titleB\x06\n" +
	"\x04_skuB\x13\n" +
	"\x11_inventory_policyB\x12\n" +
	"\x10_allow_backorderB\n" +
	"\n" +
	"\b_option1B\n" +
	"\n" +
	"\b_option2B\n" +
	"\n" +
	"\b_option3B\x13\n" +
	"\x11_duration_minutesB\t\n" +
	"\a_formatB\f\n" +
	"\n" +
	"_max_seatsB\n" +
	"\n" +
	"\b_updates\"\xc6\x05\n" +
	"\x15UpdateVariantResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x01R\x03sku\x88\x01\x01\x12h\n" +
	"\x10inventory_policy\x18\x04 \x01(\x0e28.proto.product_service.variant.v1.VariantInventoryPolicyH\x02R\x0finventoryPolicy\x88\x01\x01\x12,\n" +
	"\x0fallow_backorder\x18\x05 \x01(\bH\x03R\x0eallowBackorder\x88\x01\x01\x12\x1d\n" +
	"\aoption1\x18\x06 \x01(\tH\x04R\aoption1\x88\x01\x01\x12\x1d\n" +
	"\aoption2\x18\a \x01(\tH\x05R\aoption2\x88\x01\x01\x12\x1d\n" +
	"\aoption3\x18\b \x01(\tH\x06R\aoption3\x88\x01\x01\x12.\n" +
	"\x10duration_minutes\x18\t \x01(\x05H\aR\x0fdurationMinutes\x88\x01\x01\x12L\n" +
	"\x06format\x18\n" +
	" \x01(\x0e2/.proto.product_service.variant.v1.VariantFormatH\bR\x06format\x88\x01\x01\x12 \n" +
	"\tmax_seats\x18\v \x01(\x05H\tR\bmaxSeats\x88\x01\x01\x129\n" +
	"\aupdates\x18\f \x01(\v2\x1a.google.protobuf.FieldMaskH\n" +
	"R\aupdates\x88\x01\x01B\b\n" +
	"\x06_titleB\x06\n" +
	"\x04_skuB\x13\n" +
	"\x11_inventory_policyB\x12\n" +
	"\x10_allow_backorderB\n" +
	"\n" +
	"\b_option1B\n" +
	"\n" +
	"\b_option2B\n" +
	"\n" +
	"\b_option3B\x13\n" +
	"\x11_duration_minutesB\t\n" +
	"\a_formatB\f\n" +
	"\n" +
	"_max_seatsB\n" +
	"\n" +
	"\b_updates\"v\n" +
	"\x0ePublishRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x02 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x03 \x01(\tR\tadminName\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"\x11\n" +
	"\x0fPublishResponse\"\r\n" +
	"\vPingRequest\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2\xd4\x05\n" +
	"\x0fTrainingService\x12g\n" +
	"\x04Ping\x12..proto.product_service.training.v1.PingRequest\x1a/.proto.product_service.training.v1.PingResponse\x12m\n" +
	"\x06Create\x120.proto.product_service.training.v1.CreateRequest\x1a1.proto.product_service.training.v1.CreateResponse\x12m\n" +
	"\x06Update\x120.proto.product_service.training.v1.UpdateRequest\x1a1.proto.product_service.training.v1.UpdateResponse\x12\x82\x01\n" +
	"\rCreateVariant\x127.proto.product_service.training.v1.CreateVariantRequest\x1a8.proto.product_service.training.v1.CreateVariantResponse\x12\x82\x01\n" +
	"\rUpdateVariant\x127.proto.product_service.training.v1.UpdateVariantRequest\x1a8.proto.product_service.training.v1.UpdateVariantResponse\x12p\n" +
	"\aPublish\x121.proto.product_service.training.v1.PublishRequest\x1a2.proto.product_service.training.v1.PublishResponseB\xb8\x02\n" +
	"%com.proto.product_service.training.v1B\rTrainingProtoP\x01Z]github.com/mikhail5545/product-service-client/pb/proto/product_service/training/v1;trainingv1\xa2\x02\x03PPT\xaa\x02 Proto.ProductService.Training.V1\xca\x02 Proto\\ProductService\\Training\\V1\xe2\x02,Proto\\ProductService\\Training\\V1\\GPBMetadata\xea\x02#Proto::ProductService::Training::V1b\x06proto3"

var (
	file_proto_product_service_training_v1_training_proto_rawDescOnce sync.Once
	file_proto_product_service_training_v1_training_proto_rawDescData []byte
)

func file_proto_product_service_training_v1_training_proto_rawDescGZIP() []byte {
	file_proto_product_service_training_v1_training_proto_rawDescOnce.Do(func() {
		file_proto_product_service_training_v1_training_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_service_training_v1_training_proto_rawDesc), len(file_proto_product_service_training_v1_training_proto_rawDesc)))
	})
	return file_proto_product_service_training_v1_training_proto_rawDescData
}

var file_proto_product_service_training_v1_training_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_product_service_training_v1_training_proto_goTypes = []any{
	(*CreateRequest)(nil),           // 0: proto.product_service.training.v1.CreateRequest
	(*CreateResponse)(nil),          // 1: proto.product_service.training.v1.CreateResponse
	(*UpdateRequest)(nil),           // 2: proto.product_service.training.v1.UpdateRequest
	(*UpdateResponse)(nil),          // 3: proto.product_service.training.v1.UpdateResponse
	(*CreateVariantRequest)(nil),    // 4: proto.product_service.training.v1.CreateVariantRequest
	(*CreateVariantResponse)(nil),   // 5: proto.product_service.training.v1.CreateVariantResponse
	(*UpdateVariantRequest)(nil),    // 6: proto.product_service.training.v1.UpdateVariantRequest
	(*UpdateVariantResponse)(nil),   // 7: proto.product_service.training.v1.UpdateVariantResponse
	(*PublishRequest)(nil),          // 8: proto.product_service.training.v1.PublishRequest
	(*PublishResponse)(nil),         // 9: proto.product_service.training.v1.PublishResponse
	(*PingRequest)(nil),             // 10: proto.product_service.training.v1.PingRequest
	(*PingResponse)(nil),            // 11: proto.product_service.training.v1.PingResponse
	(*v1.Product)(nil),              // 12: proto.product_service.product.v1.Product
	(*fieldmaskpb.FieldMask)(nil),   // 13: google.protobuf.FieldMask
	(v11.VariantFormat)(0),          // 14: proto.product_service.variant.v1.VariantFormat
	(*v11.Variant)(nil),             // 15: proto.product_service.variant.v1.Variant
	(v11.VariantInventoryPolicy)(0), // 16: proto.product_service.variant.v1.VariantInventoryPolicy
}
var file_proto_product_service_training_v1_training_proto_depIdxs = []int32{
	12, // 0: proto.product_service.training.v1.CreateResponse.product:type_name -> proto.product_service.product.v1.Product
	13, // 1: proto.product_service.training.v1.UpdateRequest.updates:type_name -> google.protobuf.FieldMask
	13, // 2: proto.product_service.training.v1.UpdateResponse.updates:type_name -> google.protobuf.FieldMask
	14, // 3: proto.product_service.training.v1.CreateVariantRequest.format:type_name -> proto.product_service.variant.v1.VariantFormat
	15, // 4: proto.product_service.training.v1.CreateVariantResponse.variant:type_name -> proto.product_service.variant.v1.Variant
	16, // 5: proto.product_service.training.v1.UpdateVariantRequest.inventory_policy:type_name -> proto.product_service.variant.v1.VariantInventoryPolicy
	14, // 6: proto.product_service.training.v1.UpdateVariantRequest.format:type_name -> proto.product_service.variant.v1.VariantFormat
	13, // 7: proto.product_service.training.v1.UpdateVariantRequest.updates:type_name -> google.protobuf.FieldMask
	16, // 8: proto.product_service.training.v1.UpdateVariantResponse.inventory_policy:type_name -> proto.product_service.variant.v1.VariantInventoryPolicy
	14, // 9: proto.product_service.training.v1.UpdateVariantResponse.format:type_name -> proto.product_service.variant.v1.VariantFormat
	13, // 10: proto.product_service.training.v1.UpdateVariantResponse.updates:type_name -> google.protobuf.FieldMask
	10, // 11: proto.product_service.training.v1.TrainingService.Ping:input_type -> proto.product_service.training.v1.PingRequest
	0,  // 12: proto.product_service.training.v1.TrainingService.Create:input_type -> proto.product_service.training.v1.CreateRequest
	2,  // 13: proto.product_service.training.v1.TrainingService.Update:input_type -> proto.product_service.training.v1.UpdateRequest
	4,  // 14: proto.product_service.training.v1.TrainingService.CreateVariant:input_type -> proto.product_service.training.v1.CreateVariantRequest
	6,  // 15: proto.product_service.training.v1.TrainingService.UpdateVariant:input_type -> proto.product_service.training.v1.UpdateVariantRequest
	8,  // 16: proto.product_service.training.v1.TrainingService.Publish:input_type -> proto.product_service.training.v1.PublishRequest
	11, // 17: proto.product_service.training.v1.TrainingService.Ping:output_type -> proto.product_service.training.v1.PingResponse
	1,  // 18: proto.product_service.training.v1.TrainingService.Create:output_type -> proto.product_service.training.v1.CreateResponse
	3,  // 19: proto.product_service.training.v1.TrainingService.Update:output_type -> proto.product_service.training.v1.UpdateResponse
	5,  // 20: proto.product_service.training.v1.TrainingService.CreateVariant:output_type -> proto.product_service.training.v1.CreateVariantResponse
	7,  // 21: proto.product_service.training.v1.TrainingService.UpdateVariant:output_type -> proto.product_service.training.v1.UpdateVariantResponse
	9,  // 22: proto.product_service.training.v1.TrainingService.Publish:output_type -> proto.product_service.training.v1.PublishResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_product_service_training_v1_training_proto_init() }
func file_proto_product_service_training_v1_training_proto_init() {
	if File_proto_product_service_training_v1_training_proto != nil {
		return
	}
	file_proto_product_service_training_v1_training_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_product_service_training_v1_training_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_product_service_training_v1_training_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_product_service_training_v1_training_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_product_service_training_v1_training_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_product_service_training_v1_training_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_service_training_v1_training_proto_rawDesc), len(file_proto_product_service_training_v1_training_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_service_training_v1_training_proto_goTypes,
		DependencyIndexes: file_proto_product_service_training_v1_training_proto_depIdxs,
		MessageInfos:      file_proto_product_service_training_v1_training_proto_msgTypes,
	}.Build()
	File_proto_product_service_training_v1_training_proto = out.File
	file_proto_product_service_training_v1_training_proto_goTypes = nil
	file_proto_product_service_training_v1_training_proto_depIdxs = nil
}
