// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: product_service/lesson/lesson_video_version/v1/lesson_video_version.proto

package lesson_video_versionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LessonVideoVersionService_Ping_FullMethodName           = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/Ping"
	LessonVideoVersionService_List_FullMethodName           = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/List"
	LessonVideoVersionService_ListDrafts_FullMethodName     = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/ListDrafts"
	LessonVideoVersionService_ListSuperseded_FullMethodName = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/ListSuperseded"
	LessonVideoVersionService_ListArchived_FullMethodName   = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/ListArchived"
	LessonVideoVersionService_Associate_FullMethodName      = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/Associate"
	LessonVideoVersionService_Publish_FullMethodName        = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/Publish"
	LessonVideoVersionService_DeleteDraft_FullMethodName    = "/product_service.lesson.lesson_video_version.v1.LessonVideoVersionService/DeleteDraft"
)

// LessonVideoVersionServiceClient is the client API for LessonVideoVersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LessonVideoVersionServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ListDrafts(ctx context.Context, in *ListDraftsRequest, opts ...grpc.CallOption) (*ListDraftsResponse, error)
	ListSuperseded(ctx context.Context, in *ListSupersededRequest, opts ...grpc.CallOption) (*ListSupersededResponse, error)
	ListArchived(ctx context.Context, in *ListArchivedRequest, opts ...grpc.CallOption) (*ListArchivedResponse, error)
	Associate(ctx context.Context, in *AssociateRequest, opts ...grpc.CallOption) (*AssociateResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*DeleteDraftResponse, error)
}

type lessonVideoVersionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLessonVideoVersionServiceClient(cc grpc.ClientConnInterface) LessonVideoVersionServiceClient {
	return &lessonVideoVersionServiceClient{cc}
}

func (c *lessonVideoVersionServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonVideoVersionServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonVideoVersionServiceClient) ListDrafts(ctx context.Context, in *ListDraftsRequest, opts ...grpc.CallOption) (*ListDraftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDraftsResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_ListDrafts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonVideoVersionServiceClient) ListSuperseded(ctx context.Context, in *ListSupersededRequest, opts ...grpc.CallOption) (*ListSupersededResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupersededResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_ListSuperseded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonVideoVersionServiceClient) ListArchived(ctx context.Context, in *ListArchivedRequest, opts ...grpc.CallOption) (*ListArchivedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArchivedResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_ListArchived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonVideoVersionServiceClient) Associate(ctx context.Context, in *AssociateRequest, opts ...grpc.CallOption) (*AssociateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssociateResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_Associate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonVideoVersionServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonVideoVersionServiceClient) DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*DeleteDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDraftResponse)
	err := c.cc.Invoke(ctx, LessonVideoVersionService_DeleteDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LessonVideoVersionServiceServer is the server API for LessonVideoVersionService service.
// All implementations must embed UnimplementedLessonVideoVersionServiceServer
// for forward compatibility.
type LessonVideoVersionServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	ListDrafts(context.Context, *ListDraftsRequest) (*ListDraftsResponse, error)
	ListSuperseded(context.Context, *ListSupersededRequest) (*ListSupersededResponse, error)
	ListArchived(context.Context, *ListArchivedRequest) (*ListArchivedResponse, error)
	Associate(context.Context, *AssociateRequest) (*AssociateResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	DeleteDraft(context.Context, *DeleteDraftRequest) (*DeleteDraftResponse, error)
	mustEmbedUnimplementedLessonVideoVersionServiceServer()
}

// UnimplementedLessonVideoVersionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLessonVideoVersionServiceServer struct{}

func (UnimplementedLessonVideoVersionServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) ListDrafts(context.Context, *ListDraftsRequest) (*ListDraftsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrafts not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) ListSuperseded(context.Context, *ListSupersededRequest) (*ListSupersededResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSuperseded not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) ListArchived(context.Context, *ListArchivedRequest) (*ListArchivedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArchived not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) Associate(context.Context, *AssociateRequest) (*AssociateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Associate not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) DeleteDraft(context.Context, *DeleteDraftRequest) (*DeleteDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDraft not implemented")
}
func (UnimplementedLessonVideoVersionServiceServer) mustEmbedUnimplementedLessonVideoVersionServiceServer() {
}
func (UnimplementedLessonVideoVersionServiceServer) testEmbeddedByValue() {}

// UnsafeLessonVideoVersionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LessonVideoVersionServiceServer will
// result in compilation errors.
type UnsafeLessonVideoVersionServiceServer interface {
	mustEmbedUnimplementedLessonVideoVersionServiceServer()
}

func RegisterLessonVideoVersionServiceServer(s grpc.ServiceRegistrar, srv LessonVideoVersionServiceServer) {
	// If the following call panics, it indicates UnimplementedLessonVideoVersionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LessonVideoVersionService_ServiceDesc, srv)
}

func _LessonVideoVersionService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonVideoVersionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonVideoVersionService_ListDrafts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDraftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).ListDrafts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_ListDrafts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).ListDrafts(ctx, req.(*ListDraftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonVideoVersionService_ListSuperseded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupersededRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).ListSuperseded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_ListSuperseded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).ListSuperseded(ctx, req.(*ListSupersededRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonVideoVersionService_ListArchived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).ListArchived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_ListArchived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).ListArchived(ctx, req.(*ListArchivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonVideoVersionService_Associate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssociateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).Associate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_Associate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).Associate(ctx, req.(*AssociateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonVideoVersionService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonVideoVersionService_DeleteDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonVideoVersionServiceServer).DeleteDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LessonVideoVersionService_DeleteDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonVideoVersionServiceServer).DeleteDraft(ctx, req.(*DeleteDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LessonVideoVersionService_ServiceDesc is the grpc.ServiceDesc for LessonVideoVersionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LessonVideoVersionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_service.lesson.lesson_video_version.v1.LessonVideoVersionService",
	HandlerType: (*LessonVideoVersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LessonVideoVersionService_Ping_Handler,
		},
		{
			MethodName: "List",
			Handler:    _LessonVideoVersionService_List_Handler,
		},
		{
			MethodName: "ListDrafts",
			Handler:    _LessonVideoVersionService_ListDrafts_Handler,
		},
		{
			MethodName: "ListSuperseded",
			Handler:    _LessonVideoVersionService_ListSuperseded_Handler,
		},
		{
			MethodName: "ListArchived",
			Handler:    _LessonVideoVersionService_ListArchived_Handler,
		},
		{
			MethodName: "Associate",
			Handler:    _LessonVideoVersionService_Associate_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _LessonVideoVersionService_Publish_Handler,
		},
		{
			MethodName: "DeleteDraft",
			Handler:    _LessonVideoVersionService_DeleteDraft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_service/lesson/lesson_video_version/v1/lesson_video_version.proto",
}
