// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: product_service/variant/v1/variant.proto

package variantv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VariantService_Ping_FullMethodName             = "/product_service.variant.v1.VariantService/Ping"
	VariantService_Get_FullMethodName              = "/product_service.variant.v1.VariantService/Get"
	VariantService_GetWithScheduled_FullMethodName = "/product_service.variant.v1.VariantService/GetWithScheduled"
	VariantService_GetWithDraft_FullMethodName     = "/product_service.variant.v1.VariantService/GetWithDraft"
	VariantService_GetWithArchived_FullMethodName  = "/product_service.variant.v1.VariantService/GetWithArchived"
	VariantService_List_FullMethodName             = "/product_service.variant.v1.VariantService/List"
	VariantService_ListScheduled_FullMethodName    = "/product_service.variant.v1.VariantService/ListScheduled"
	VariantService_ListDrafts_FullMethodName       = "/product_service.variant.v1.VariantService/ListDrafts"
	VariantService_ListArchived_FullMethodName     = "/product_service.variant.v1.VariantService/ListArchived"
	VariantService_Publish_FullMethodName          = "/product_service.variant.v1.VariantService/Publish"
	VariantService_Archive_FullMethodName          = "/product_service.variant.v1.VariantService/Archive"
	VariantService_Restore_FullMethodName          = "/product_service.variant.v1.VariantService/Restore"
)

// VariantServiceClient is the client API for VariantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VariantServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetWithScheduled(ctx context.Context, in *GetWithScheduledRequest, opts ...grpc.CallOption) (*GetWithScheduledResponse, error)
	GetWithDraft(ctx context.Context, in *GetWithDraftRequest, opts ...grpc.CallOption) (*GetWithDraftResponse, error)
	GetWithArchived(ctx context.Context, in *GetWithArchivedRequest, opts ...grpc.CallOption) (*GetWithArchivedResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ListScheduled(ctx context.Context, in *ListScheduledRequest, opts ...grpc.CallOption) (*ListScheduledResponse, error)
	ListDrafts(ctx context.Context, in *ListDraftsRequest, opts ...grpc.CallOption) (*ListDraftsResponse, error)
	ListArchived(ctx context.Context, in *ListArchivedRequest, opts ...grpc.CallOption) (*ListArchivedResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
}

type variantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVariantServiceClient(cc grpc.ClientConnInterface) VariantServiceClient {
	return &variantServiceClient{cc}
}

func (c *variantServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, VariantService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, VariantService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) GetWithScheduled(ctx context.Context, in *GetWithScheduledRequest, opts ...grpc.CallOption) (*GetWithScheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithScheduledResponse)
	err := c.cc.Invoke(ctx, VariantService_GetWithScheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) GetWithDraft(ctx context.Context, in *GetWithDraftRequest, opts ...grpc.CallOption) (*GetWithDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithDraftResponse)
	err := c.cc.Invoke(ctx, VariantService_GetWithDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) GetWithArchived(ctx context.Context, in *GetWithArchivedRequest, opts ...grpc.CallOption) (*GetWithArchivedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithArchivedResponse)
	err := c.cc.Invoke(ctx, VariantService_GetWithArchived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, VariantService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) ListScheduled(ctx context.Context, in *ListScheduledRequest, opts ...grpc.CallOption) (*ListScheduledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScheduledResponse)
	err := c.cc.Invoke(ctx, VariantService_ListScheduled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) ListDrafts(ctx context.Context, in *ListDraftsRequest, opts ...grpc.CallOption) (*ListDraftsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDraftsResponse)
	err := c.cc.Invoke(ctx, VariantService_ListDrafts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) ListArchived(ctx context.Context, in *ListArchivedRequest, opts ...grpc.CallOption) (*ListArchivedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArchivedResponse)
	err := c.cc.Invoke(ctx, VariantService_ListArchived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, VariantService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) Archive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveResponse)
	err := c.cc.Invoke(ctx, VariantService_Archive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, VariantService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VariantServiceServer is the server API for VariantService service.
// All implementations must embed UnimplementedVariantServiceServer
// for forward compatibility.
type VariantServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetWithScheduled(context.Context, *GetWithScheduledRequest) (*GetWithScheduledResponse, error)
	GetWithDraft(context.Context, *GetWithDraftRequest) (*GetWithDraftResponse, error)
	GetWithArchived(context.Context, *GetWithArchivedRequest) (*GetWithArchivedResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	ListScheduled(context.Context, *ListScheduledRequest) (*ListScheduledResponse, error)
	ListDrafts(context.Context, *ListDraftsRequest) (*ListDraftsResponse, error)
	ListArchived(context.Context, *ListArchivedRequest) (*ListArchivedResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	mustEmbedUnimplementedVariantServiceServer()
}

// UnimplementedVariantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVariantServiceServer struct{}

func (UnimplementedVariantServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVariantServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVariantServiceServer) GetWithScheduled(context.Context, *GetWithScheduledRequest) (*GetWithScheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithScheduled not implemented")
}
func (UnimplementedVariantServiceServer) GetWithDraft(context.Context, *GetWithDraftRequest) (*GetWithDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithDraft not implemented")
}
func (UnimplementedVariantServiceServer) GetWithArchived(context.Context, *GetWithArchivedRequest) (*GetWithArchivedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithArchived not implemented")
}
func (UnimplementedVariantServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVariantServiceServer) ListScheduled(context.Context, *ListScheduledRequest) (*ListScheduledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScheduled not implemented")
}
func (UnimplementedVariantServiceServer) ListDrafts(context.Context, *ListDraftsRequest) (*ListDraftsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrafts not implemented")
}
func (UnimplementedVariantServiceServer) ListArchived(context.Context, *ListArchivedRequest) (*ListArchivedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArchived not implemented")
}
func (UnimplementedVariantServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedVariantServiceServer) Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedVariantServiceServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedVariantServiceServer) mustEmbedUnimplementedVariantServiceServer() {}
func (UnimplementedVariantServiceServer) testEmbeddedByValue()                        {}

// UnsafeVariantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VariantServiceServer will
// result in compilation errors.
type UnsafeVariantServiceServer interface {
	mustEmbedUnimplementedVariantServiceServer()
}

func RegisterVariantServiceServer(s grpc.ServiceRegistrar, srv VariantServiceServer) {
	// If the following call panics, it indicates UnimplementedVariantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VariantService_ServiceDesc, srv)
}

func _VariantService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_GetWithScheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithScheduledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).GetWithScheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_GetWithScheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).GetWithScheduled(ctx, req.(*GetWithScheduledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_GetWithDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).GetWithDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_GetWithDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).GetWithDraft(ctx, req.(*GetWithDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_GetWithArchived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithArchivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).GetWithArchived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_GetWithArchived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).GetWithArchived(ctx, req.(*GetWithArchivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_ListScheduled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScheduledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).ListScheduled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_ListScheduled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).ListScheduled(ctx, req.(*ListScheduledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_ListDrafts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDraftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).ListDrafts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_ListDrafts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).ListDrafts(ctx, req.(*ListDraftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_ListArchived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).ListArchived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_ListArchived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).ListArchived(ctx, req.(*ListArchivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_Archive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).Archive(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VariantService_ServiceDesc is the grpc.ServiceDesc for VariantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VariantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_service.variant.v1.VariantService",
	HandlerType: (*VariantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _VariantService_Ping_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VariantService_Get_Handler,
		},
		{
			MethodName: "GetWithScheduled",
			Handler:    _VariantService_GetWithScheduled_Handler,
		},
		{
			MethodName: "GetWithDraft",
			Handler:    _VariantService_GetWithDraft_Handler,
		},
		{
			MethodName: "GetWithArchived",
			Handler:    _VariantService_GetWithArchived_Handler,
		},
		{
			MethodName: "List",
			Handler:    _VariantService_List_Handler,
		},
		{
			MethodName: "ListScheduled",
			Handler:    _VariantService_ListScheduled_Handler,
		},
		{
			MethodName: "ListDrafts",
			Handler:    _VariantService_ListDrafts_Handler,
		},
		{
			MethodName: "ListArchived",
			Handler:    _VariantService_ListArchived_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _VariantService_Publish_Handler,
		},
		{
			MethodName: "Archive",
			Handler:    _VariantService_Archive_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _VariantService_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_service/variant/v1/variant.proto",
}
