// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/product_service/video/v1/video.proto

package videov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoStatus int32

const (
	VideoStatus_VIDEO_STATUS_UNSPECIFIED VideoStatus = 0
	VideoStatus_VIDEO_STATUS_ACTIVE      VideoStatus = 1
	VideoStatus_VIDEO_STATUS_BROKEN      VideoStatus = 2
)

// Enum value maps for VideoStatus.
var (
	VideoStatus_name = map[int32]string{
		0: "VIDEO_STATUS_UNSPECIFIED",
		1: "VIDEO_STATUS_ACTIVE",
		2: "VIDEO_STATUS_BROKEN",
	}
	VideoStatus_value = map[string]int32{
		"VIDEO_STATUS_UNSPECIFIED": 0,
		"VIDEO_STATUS_ACTIVE":      1,
		"VIDEO_STATUS_BROKEN":      2,
	}
)

func (x VideoStatus) Enum() *VideoStatus {
	p := new(VideoStatus)
	*p = x
	return p
}

func (x VideoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_service_video_v1_video_proto_enumTypes[0].Descriptor()
}

func (VideoStatus) Type() protoreflect.EnumType {
	return &file_proto_product_service_video_v1_video_proto_enumTypes[0]
}

func (x VideoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoStatus.Descriptor instead.
func (VideoStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_service_video_v1_video_proto_rawDescGZIP(), []int{0}
}

type UploadStatus int32

const (
	UploadStatus_UPLOAD_STATUS_UNSPECIFIED UploadStatus = 0
	UploadStatus_UPLOAD_STATUS_PREPARING   UploadStatus = 1
	UploadStatus_UPLOAD_STATUS_READY       UploadStatus = 2
	UploadStatus_UPLOAD_STATUS_ERRORED     UploadStatus = 3
)

// Enum value maps for UploadStatus.
var (
	UploadStatus_name = map[int32]string{
		0: "UPLOAD_STATUS_UNSPECIFIED",
		1: "UPLOAD_STATUS_PREPARING",
		2: "UPLOAD_STATUS_READY",
		3: "UPLOAD_STATUS_ERRORED",
	}
	UploadStatus_value = map[string]int32{
		"UPLOAD_STATUS_UNSPECIFIED": 0,
		"UPLOAD_STATUS_PREPARING":   1,
		"UPLOAD_STATUS_READY":       2,
		"UPLOAD_STATUS_ERRORED":     3,
	}
)

func (x UploadStatus) Enum() *UploadStatus {
	p := new(UploadStatus)
	*p = x
	return p
}

func (x UploadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_service_video_v1_video_proto_enumTypes[1].Descriptor()
}

func (UploadStatus) Type() protoreflect.EnumType {
	return &file_proto_product_service_video_v1_video_proto_enumTypes[1]
}

func (x UploadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatus.Descriptor instead.
func (UploadStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_service_video_v1_video_proto_rawDescGZIP(), []int{1}
}

type Video struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	MediaServiceUuid []byte                 `protobuf:"bytes,5,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	PublicPlaybackId *string                `protobuf:"bytes,6,opt,name=public_playback_id,json=publicPlaybackId,proto3,oneof" json:"public_playback_id,omitempty"`
	SignedPlaybackId string                 `protobuf:"bytes,7,opt,name=signed_playback_id,json=signedPlaybackId,proto3" json:"signed_playback_id,omitempty"`
	DurationSeconds  float32                `protobuf:"fixed32,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AspectRatio      *string                `protobuf:"bytes,9,opt,name=aspect_ratio,json=aspectRatio,proto3,oneof" json:"aspect_ratio,omitempty"`
	ThumbnailUrl     *string                `protobuf:"bytes,10,opt,name=thumbnail_url,json=thumbnailUrl,proto3,oneof" json:"thumbnail_url,omitempty"`
	Status           VideoStatus            `protobuf:"varint,11,opt,name=status,proto3,enum=proto.product_service.video.v1.VideoStatus" json:"status,omitempty"`
	UploadStatus     UploadStatus           `protobuf:"varint,12,opt,name=upload_status,json=uploadStatus,proto3,enum=proto.product_service.video.v1.UploadStatus" json:"upload_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_product_service_video_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Video) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Video) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Video) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Video) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

func (x *Video) GetPublicPlaybackId() string {
	if x != nil && x.PublicPlaybackId != nil {
		return *x.PublicPlaybackId
	}
	return ""
}

func (x *Video) GetSignedPlaybackId() string {
	if x != nil {
		return x.SignedPlaybackId
	}
	return ""
}

func (x *Video) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Video) GetAspectRatio() string {
	if x != nil && x.AspectRatio != nil {
		return *x.AspectRatio
	}
	return ""
}

func (x *Video) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *Video) GetStatus() VideoStatus {
	if x != nil {
		return x.Status
	}
	return VideoStatus_VIDEO_STATUS_UNSPECIFIED
}

func (x *Video) GetUploadStatus() UploadStatus {
	if x != nil {
		return x.UploadStatus
	}
	return UploadStatus_UPLOAD_STATUS_UNSPECIFIED
}

type BrokenVideoRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaServiceUuid []byte                 `protobuf:"bytes,1,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminUuid        []byte                 `protobuf:"bytes,3,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName        string                 `protobuf:"bytes,4,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BrokenVideoRequest) Reset() {
	*x = BrokenVideoRequest{}
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokenVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenVideoRequest) ProtoMessage() {}

func (x *BrokenVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenVideoRequest.ProtoReflect.Descriptor instead.
func (*BrokenVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_video_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *BrokenVideoRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

func (x *BrokenVideoRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BrokenVideoRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *BrokenVideoRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type BrokenVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokenVideoResponse) Reset() {
	*x = BrokenVideoResponse{}
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokenVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenVideoResponse) ProtoMessage() {}

func (x *BrokenVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenVideoResponse.ProtoReflect.Descriptor instead.
func (*BrokenVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_video_v1_video_proto_rawDescGZIP(), []int{2}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_video_v1_video_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_video_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_video_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_product_service_video_v1_video_proto protoreflect.FileDescriptor

const file_proto_product_service_video_v1_video_proto_rawDesc = "" +
	"\n" +
	"*proto/product_service/video/v1/video.proto\x12\x1eproto.product_service.video.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x05\n" +
	"\x05Video\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12,\n" +
	"\x12media_service_uuid\x18\x05 \x01(\fR\x10mediaServiceUuid\x121\n" +
	"\x12public_playback_id\x18\x06 \x01(\tH\x01R\x10publicPlaybackId\x88\x01\x01\x12,\n" +
	"\x12signed_playback_id\x18\a \x01(\tR\x10signedPlaybackId\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x02R\x0fdurationSeconds\x12&\n" +
	"\faspect_ratio\x18\t \x01(\tH\x02R\vaspectRatio\x88\x01\x01\x12(\n" +
	"\rthumbnail_url\x18\n" +
	" \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01\x12C\n" +
	"\x06status\x18\v \x01(\x0e2+.proto.product_service.video.v1.VideoStatusR\x06status\x12Q\n" +
	"\rupload_status\x18\f \x01(\x0e2,.proto.product_service.video.v1.UploadStatusR\fuploadStatusB\r\n" +
	"\v_deleted_atB\x15\n" +
	"\x13_public_playback_idB\x0f\n" +
	"\r_aspect_ratioB\x10\n" +
	"\x0e_thumbnail_url\"\x98\x01\n" +
	"\x12BrokenVideoRequest\x12,\n" +
	"\x12media_service_uuid\x18\x01 \x01(\fR\x10mediaServiceUuid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x03 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x04 \x01(\tR\tadminName\"\x15\n" +
	"\x13BrokenVideoResponse\"\r\n" +
	"\vPingRequest\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp*]\n" +
	"\vVideoStatus\x12\x1c\n" +
	"\x18VIDEO_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13VIDEO_STATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13VIDEO_STATUS_BROKEN\x10\x02*~\n" +
	"\fUploadStatus\x12\x1d\n" +
	"\x19UPLOAD_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17UPLOAD_STATUS_PREPARING\x10\x01\x12\x17\n" +
	"\x13UPLOAD_STATUS_READY\x10\x02\x12\x19\n" +
	"\x15UPLOAD_STATUS_ERRORED\x10\x032\xe9\x01\n" +
	"\fVideoService\x12a\n" +
	"\x04Ping\x12+.proto.product_service.video.v1.PingRequest\x1a,.proto.product_service.video.v1.PingResponse\x12v\n" +
	"\vBrokenVideo\x122.proto.product_service.video.v1.BrokenVideoRequest\x1a3.proto.product_service.video.v1.BrokenVideoResponseB\xa0\x02\n" +
	"\"com.proto.product_service.video.v1B\n" +
	"VideoProtoP\x01ZWgithub.com/mikhail5545/product-service-client/pb/proto/product_service/video/v1;videov1\xa2\x02\x03PPV\xaa\x02\x1dProto.ProductService.Video.V1\xca\x02\x1dProto\\ProductService\\Video\\V1\xe2\x02)Proto\\ProductService\\Video\\V1\\GPBMetadata\xea\x02 Proto::ProductService::Video::V1b\x06proto3"

var (
	file_proto_product_service_video_v1_video_proto_rawDescOnce sync.Once
	file_proto_product_service_video_v1_video_proto_rawDescData []byte
)

func file_proto_product_service_video_v1_video_proto_rawDescGZIP() []byte {
	file_proto_product_service_video_v1_video_proto_rawDescOnce.Do(func() {
		file_proto_product_service_video_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_service_video_v1_video_proto_rawDesc), len(file_proto_product_service_video_v1_video_proto_rawDesc)))
	})
	return file_proto_product_service_video_v1_video_proto_rawDescData
}

var file_proto_product_service_video_v1_video_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_product_service_video_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_product_service_video_v1_video_proto_goTypes = []any{
	(VideoStatus)(0),              // 0: proto.product_service.video.v1.VideoStatus
	(UploadStatus)(0),             // 1: proto.product_service.video.v1.UploadStatus
	(*Video)(nil),                 // 2: proto.product_service.video.v1.Video
	(*BrokenVideoRequest)(nil),    // 3: proto.product_service.video.v1.BrokenVideoRequest
	(*BrokenVideoResponse)(nil),   // 4: proto.product_service.video.v1.BrokenVideoResponse
	(*PingRequest)(nil),           // 5: proto.product_service.video.v1.PingRequest
	(*PingResponse)(nil),          // 6: proto.product_service.video.v1.PingResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_product_service_video_v1_video_proto_depIdxs = []int32{
	7, // 0: proto.product_service.video.v1.Video.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: proto.product_service.video.v1.Video.updated_at:type_name -> google.protobuf.Timestamp
	7, // 2: proto.product_service.video.v1.Video.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 3: proto.product_service.video.v1.Video.status:type_name -> proto.product_service.video.v1.VideoStatus
	1, // 4: proto.product_service.video.v1.Video.upload_status:type_name -> proto.product_service.video.v1.UploadStatus
	5, // 5: proto.product_service.video.v1.VideoService.Ping:input_type -> proto.product_service.video.v1.PingRequest
	3, // 6: proto.product_service.video.v1.VideoService.BrokenVideo:input_type -> proto.product_service.video.v1.BrokenVideoRequest
	6, // 7: proto.product_service.video.v1.VideoService.Ping:output_type -> proto.product_service.video.v1.PingResponse
	4, // 8: proto.product_service.video.v1.VideoService.BrokenVideo:output_type -> proto.product_service.video.v1.BrokenVideoResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_product_service_video_v1_video_proto_init() }
func file_proto_product_service_video_v1_video_proto_init() {
	if File_proto_product_service_video_v1_video_proto != nil {
		return
	}
	file_proto_product_service_video_v1_video_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_service_video_v1_video_proto_rawDesc), len(file_proto_product_service_video_v1_video_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_service_video_v1_video_proto_goTypes,
		DependencyIndexes: file_proto_product_service_video_v1_video_proto_depIdxs,
		EnumInfos:         file_proto_product_service_video_v1_video_proto_enumTypes,
		MessageInfos:      file_proto_product_service_video_v1_video_proto_msgTypes,
	}.Build()
	File_proto_product_service_video_v1_video_proto = out.File
	file_proto_product_service_video_v1_video_proto_goTypes = nil
	file_proto_product_service_video_v1_video_proto_depIdxs = nil
}
