// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: product_service/variant/variant_price/v1/variant_price.proto

package variant_pricev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VariantPriceService_Ping_FullMethodName           = "/product_service.variant.variant_price.v1.VariantPriceService/Ping"
	VariantPriceService_Get_FullMethodName            = "/product_service.variant.variant_price.v1.VariantPriceService/Get"
	VariantPriceService_List_FullMethodName           = "/product_service.variant.variant_price.v1.VariantPriceService/List"
	VariantPriceService_ListIrrelevant_FullMethodName = "/product_service.variant.variant_price.v1.VariantPriceService/ListIrrelevant"
	VariantPriceService_Create_FullMethodName         = "/product_service.variant.variant_price.v1.VariantPriceService/Create"
	VariantPriceService_Invalidate_FullMethodName     = "/product_service.variant.variant_price.v1.VariantPriceService/Invalidate"
)

// VariantPriceServiceClient is the client API for VariantPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VariantPriceServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ListIrrelevant(ctx context.Context, in *ListIrrelevantRequest, opts ...grpc.CallOption) (*ListIrrelevantResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error)
}

type variantPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVariantPriceServiceClient(cc grpc.ClientConnInterface) VariantPriceServiceClient {
	return &variantPriceServiceClient{cc}
}

func (c *variantPriceServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, VariantPriceService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantPriceServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, VariantPriceService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantPriceServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, VariantPriceService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantPriceServiceClient) ListIrrelevant(ctx context.Context, in *ListIrrelevantRequest, opts ...grpc.CallOption) (*ListIrrelevantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIrrelevantResponse)
	err := c.cc.Invoke(ctx, VariantPriceService_ListIrrelevant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantPriceServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, VariantPriceService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variantPriceServiceClient) Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateResponse)
	err := c.cc.Invoke(ctx, VariantPriceService_Invalidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VariantPriceServiceServer is the server API for VariantPriceService service.
// All implementations must embed UnimplementedVariantPriceServiceServer
// for forward compatibility.
type VariantPriceServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	ListIrrelevant(context.Context, *ListIrrelevantRequest) (*ListIrrelevantResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error)
	mustEmbedUnimplementedVariantPriceServiceServer()
}

// UnimplementedVariantPriceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVariantPriceServiceServer struct{}

func (UnimplementedVariantPriceServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVariantPriceServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVariantPriceServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVariantPriceServiceServer) ListIrrelevant(context.Context, *ListIrrelevantRequest) (*ListIrrelevantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIrrelevant not implemented")
}
func (UnimplementedVariantPriceServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVariantPriceServiceServer) Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedVariantPriceServiceServer) mustEmbedUnimplementedVariantPriceServiceServer() {}
func (UnimplementedVariantPriceServiceServer) testEmbeddedByValue()                             {}

// UnsafeVariantPriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VariantPriceServiceServer will
// result in compilation errors.
type UnsafeVariantPriceServiceServer interface {
	mustEmbedUnimplementedVariantPriceServiceServer()
}

func RegisterVariantPriceServiceServer(s grpc.ServiceRegistrar, srv VariantPriceServiceServer) {
	// If the following call panics, it indicates UnimplementedVariantPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VariantPriceService_ServiceDesc, srv)
}

func _VariantPriceService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantPriceServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantPriceService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantPriceServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantPriceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantPriceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantPriceService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantPriceServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantPriceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantPriceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantPriceService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantPriceServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantPriceService_ListIrrelevant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIrrelevantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantPriceServiceServer).ListIrrelevant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantPriceService_ListIrrelevant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantPriceServiceServer).ListIrrelevant(ctx, req.(*ListIrrelevantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantPriceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantPriceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantPriceService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantPriceServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariantPriceService_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariantPriceServiceServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariantPriceService_Invalidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariantPriceServiceServer).Invalidate(ctx, req.(*InvalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VariantPriceService_ServiceDesc is the grpc.ServiceDesc for VariantPriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VariantPriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_service.variant.variant_price.v1.VariantPriceService",
	HandlerType: (*VariantPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _VariantPriceService_Ping_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VariantPriceService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _VariantPriceService_List_Handler,
		},
		{
			MethodName: "ListIrrelevant",
			Handler:    _VariantPriceService_ListIrrelevant_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VariantPriceService_Create_Handler,
		},
		{
			MethodName: "Invalidate",
			Handler:    _VariantPriceService_Invalidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_service/variant/variant_price/v1/variant_price.proto",
}
