// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/product_service/variant/variant_price/v1/variant_price.proto

package variant_pricepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariantPriceSource int32

const (
	VariantPriceSource_VARIANT_PRICE_SOURCE_UNSPECIFIED    VariantPriceSource = 0
	VariantPriceSource_VARIANT_PRICE_SOURCE_MANUAL         VariantPriceSource = 1
	VariantPriceSource_VARIANT_PRICE_SOURCE_PROMOTION      VariantPriceSource = 2
	VariantPriceSource_VARIANT_PRICE_SOURCE_AUTO_CONVERTED VariantPriceSource = 3
)

// Enum value maps for VariantPriceSource.
var (
	VariantPriceSource_name = map[int32]string{
		0: "VARIANT_PRICE_SOURCE_UNSPECIFIED",
		1: "VARIANT_PRICE_SOURCE_MANUAL",
		2: "VARIANT_PRICE_SOURCE_PROMOTION",
		3: "VARIANT_PRICE_SOURCE_AUTO_CONVERTED",
	}
	VariantPriceSource_value = map[string]int32{
		"VARIANT_PRICE_SOURCE_UNSPECIFIED":    0,
		"VARIANT_PRICE_SOURCE_MANUAL":         1,
		"VARIANT_PRICE_SOURCE_PROMOTION":      2,
		"VARIANT_PRICE_SOURCE_AUTO_CONVERTED": 3,
	}
)

func (x VariantPriceSource) Enum() *VariantPriceSource {
	p := new(VariantPriceSource)
	*p = x
	return p
}

func (x VariantPriceSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariantPriceSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_enumTypes[0].Descriptor()
}

func (VariantPriceSource) Type() protoreflect.EnumType {
	return &file_proto_product_service_variant_variant_price_v1_variant_price_proto_enumTypes[0]
}

func (x VariantPriceSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariantPriceSource.Descriptor instead.
func (VariantPriceSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{0}
}

type VariantPrice struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VariantUuid       []byte                 `protobuf:"bytes,4,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	Market            string                 `protobuf:"bytes,5,opt,name=market,proto3" json:"market,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountMinor       int64                  `protobuf:"varint,7,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	ValidFrom         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_to,json=validTo,proto3,oneof" json:"valid_to,omitempty"`
	Source            VariantPriceSource     `protobuf:"varint,10,opt,name=source,proto3,enum=proto.product_service.variant.variant_price.v1.VariantPriceSource" json:"source,omitempty"`
	Note              *string                `protobuf:"bytes,11,opt,name=note,proto3,oneof" json:"note,omitempty"`
	InvalidateReason  *string                `protobuf:"bytes,12,opt,name=invalidate_reason,json=invalidateReason,proto3,oneof" json:"invalidate_reason,omitempty"`
	CreatedBy         []byte                 `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	InvalidatedBy     []byte                 `protobuf:"bytes,14,opt,name=invalidated_by,json=invalidatedBy,proto3,oneof" json:"invalidated_by,omitempty"`
	CreatedByName     *string                `protobuf:"bytes,15,opt,name=created_by_name,json=createdByName,proto3,oneof" json:"created_by_name,omitempty"`
	InvalidatedByName *string                `protobuf:"bytes,16,opt,name=invalidated_by_name,json=invalidatedByName,proto3,oneof" json:"invalidated_by_name,omitempty"`
	PromotionUuid     []byte                 `protobuf:"bytes,17,opt,name=promotion_uuid,json=promotionUuid,proto3,oneof" json:"promotion_uuid,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VariantPrice) Reset() {
	*x = VariantPrice{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantPrice) ProtoMessage() {}

func (x *VariantPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantPrice.ProtoReflect.Descriptor instead.
func (*VariantPrice) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{0}
}

func (x *VariantPrice) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *VariantPrice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VariantPrice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *VariantPrice) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *VariantPrice) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *VariantPrice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *VariantPrice) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *VariantPrice) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *VariantPrice) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *VariantPrice) GetSource() VariantPriceSource {
	if x != nil {
		return x.Source
	}
	return VariantPriceSource_VARIANT_PRICE_SOURCE_UNSPECIFIED
}

func (x *VariantPrice) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *VariantPrice) GetInvalidateReason() string {
	if x != nil && x.InvalidateReason != nil {
		return *x.InvalidateReason
	}
	return ""
}

func (x *VariantPrice) GetCreatedBy() []byte {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *VariantPrice) GetInvalidatedBy() []byte {
	if x != nil {
		return x.InvalidatedBy
	}
	return nil
}

func (x *VariantPrice) GetCreatedByName() string {
	if x != nil && x.CreatedByName != nil {
		return *x.CreatedByName
	}
	return ""
}

func (x *VariantPrice) GetInvalidatedByName() string {
	if x != nil && x.InvalidatedByName != nil {
		return *x.InvalidatedByName
	}
	return ""
}

func (x *VariantPrice) GetPromotionUuid() []byte {
	if x != nil {
		return x.PromotionUuid
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	VariantUuid   []byte                 `protobuf:"bytes,3,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	IsValid       *bool                  `protobuf:"varint,4,opt,name=is_valid,json=isValid,proto3,oneof" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *GetRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *GetRequest) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *GetRequest) GetIsValid() bool {
	if x != nil && x.IsValid != nil {
		return *x.IsValid
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantPrice  *VariantPrice          `protobuf:"bytes,1,opt,name=variant_price,json=variantPrice,proto3" json:"variant_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetVariantPrice() *VariantPrice {
	if x != nil {
		return x.VariantPrice
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuids         [][]byte               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	ProductUuids  [][]byte               `protobuf:"bytes,2,rep,name=product_uuids,json=productUuids,proto3" json:"product_uuids,omitempty"`
	VariantUuids  [][]byte               `protobuf:"bytes,3,rep,name=variant_uuids,json=variantUuids,proto3" json:"variant_uuids,omitempty"`
	Markets       []string               `protobuf:"bytes,4,rep,name=markets,proto3" json:"markets,omitempty"`
	Currencies    []string               `protobuf:"bytes,5,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Sources       []VariantPriceSource   `protobuf:"varint,6,rep,packed,name=sources,proto3,enum=proto.product_service.variant.variant_price.v1.VariantPriceSource" json:"sources,omitempty"`
	OrderBy       *string                `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDir      *string                `protobuf:"bytes,8,opt,name=order_dir,json=orderDir,proto3,oneof" json:"order_dir,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,10,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *ListRequest) GetProductUuids() [][]byte {
	if x != nil {
		return x.ProductUuids
	}
	return nil
}

func (x *ListRequest) GetVariantUuids() [][]byte {
	if x != nil {
		return x.VariantUuids
	}
	return nil
}

func (x *ListRequest) GetMarkets() []string {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ListRequest) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *ListRequest) GetSources() []VariantPriceSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListRequest) GetOrderDir() string {
	if x != nil && x.OrderDir != nil {
		return *x.OrderDir
	}
	return ""
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantPrices []*VariantPrice        `protobuf:"bytes,1,rep,name=variant_prices,json=variantPrices,proto3" json:"variant_prices,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetVariantPrices() []*VariantPrice {
	if x != nil {
		return x.VariantPrices
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListIrrelevantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuids         [][]byte               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	ProductUuids  [][]byte               `protobuf:"bytes,2,rep,name=product_uuids,json=productUuids,proto3" json:"product_uuids,omitempty"`
	VariantUuids  [][]byte               `protobuf:"bytes,3,rep,name=variant_uuids,json=variantUuids,proto3" json:"variant_uuids,omitempty"`
	Markets       []string               `protobuf:"bytes,4,rep,name=markets,proto3" json:"markets,omitempty"`
	Currencies    []string               `protobuf:"bytes,5,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Sources       []VariantPriceSource   `protobuf:"varint,6,rep,packed,name=sources,proto3,enum=proto.product_service.variant.variant_price.v1.VariantPriceSource" json:"sources,omitempty"`
	OrderBy       *string                `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDir      *string                `protobuf:"bytes,8,opt,name=order_dir,json=orderDir,proto3,oneof" json:"order_dir,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,10,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIrrelevantRequest) Reset() {
	*x = ListIrrelevantRequest{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIrrelevantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIrrelevantRequest) ProtoMessage() {}

func (x *ListIrrelevantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIrrelevantRequest.ProtoReflect.Descriptor instead.
func (*ListIrrelevantRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{5}
}

func (x *ListIrrelevantRequest) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *ListIrrelevantRequest) GetProductUuids() [][]byte {
	if x != nil {
		return x.ProductUuids
	}
	return nil
}

func (x *ListIrrelevantRequest) GetVariantUuids() [][]byte {
	if x != nil {
		return x.VariantUuids
	}
	return nil
}

func (x *ListIrrelevantRequest) GetMarkets() []string {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ListIrrelevantRequest) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *ListIrrelevantRequest) GetSources() []VariantPriceSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListIrrelevantRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListIrrelevantRequest) GetOrderDir() string {
	if x != nil && x.OrderDir != nil {
		return *x.OrderDir
	}
	return ""
}

func (x *ListIrrelevantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIrrelevantRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListIrrelevantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantPrices []*VariantPrice        `protobuf:"bytes,1,rep,name=variant_prices,json=variantPrices,proto3" json:"variant_prices,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIrrelevantResponse) Reset() {
	*x = ListIrrelevantResponse{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIrrelevantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIrrelevantResponse) ProtoMessage() {}

func (x *ListIrrelevantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIrrelevantResponse.ProtoReflect.Descriptor instead.
func (*ListIrrelevantResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{6}
}

func (x *ListIrrelevantResponse) GetVariantPrices() []*VariantPrice {
	if x != nil {
		return x.VariantPrices
	}
	return nil
}

func (x *ListIrrelevantResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantUuid   []byte                 `protobuf:"bytes,1,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,5,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,6,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRequest) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *CreateRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *CreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *CreateRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *CreateRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *CreateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantPrice  *VariantPrice          `protobuf:"bytes,1,opt,name=variant_price,json=variantPrice,proto3" json:"variant_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{8}
}

func (x *CreateResponse) GetVariantPrice() *VariantPrice {
	if x != nil {
		return x.VariantPrice
	}
	return nil
}

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,2,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,3,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{9}
}

func (x *InvalidateRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *InvalidateRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *InvalidateRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *InvalidateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type InvalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{10}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{11}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP(), []int{12}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_product_service_variant_variant_price_v1_variant_price_proto protoreflect.FileDescriptor

const file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDesc = "" +
	"\n" +
	"Bproto/product_service/variant/variant_price/v1/variant_price.proto\x12.proto.product_service.variant.variant_price.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\a\n" +
	"\fVariantPrice\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\fvariant_uuid\x18\x04 \x01(\fR\vvariantUuid\x12\x16\n" +
	"\x06market\x18\x05 \x01(\tR\x06market\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\famount_minor\x18\a \x01(\x03R\vamountMinor\x129\n" +
	"\n" +
	"valid_from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x12:\n" +
	"\bvalid_to\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\avalidTo\x88\x01\x01\x12Z\n" +
	"\x06source\x18\n" +
	" \x01(\x0e2B.proto.product_service.variant.variant_price.v1.VariantPriceSourceR\x06source\x12\x17\n" +
	"\x04note\x18\v \x01(\tH\x01R\x04note\x88\x01\x01\x120\n" +
	"\x11invalidate_reason\x18\f \x01(\tH\x02R\x10invalidateReason\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\r \x01(\fH\x03R\tcreatedBy\x88\x01\x01\x12*\n" +
	"\x0einvalidated_by\x18\x0e \x01(\fH\x04R\rinvalidatedBy\x88\x01\x01\x12+\n" +
	"\x0fcreated_by_name\x18\x0f \x01(\tH\x05R\rcreatedByName\x88\x01\x01\x123\n" +
	"\x13invalidated_by_name\x18\x10 \x01(\tH\x06R\x11invalidatedByName\x88\x01\x01\x12*\n" +
	"\x0epromotion_uuid\x18\x11 \x01(\fH\aR\rpromotionUuid\x88\x01\x01B\v\n" +
	"\t_valid_toB\a\n" +
	"\x05_noteB\x14\n" +
	"\x12_invalidate_reasonB\r\n" +
	"\v_created_byB\x11\n" +
	"\x0f_invalidated_byB\x12\n" +
	"\x10_created_by_nameB\x16\n" +
	"\x14_invalidated_by_nameB\x11\n" +
	"\x0f_promotion_uuid\"\x88\x01\n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12!\n" +
	"\fvariant_uuid\x18\x03 \x01(\fR\vvariantUuid\x12\x1e\n" +
	"\bis_valid\x18\x04 \x01(\bH\x00R\aisValid\x88\x01\x01B\v\n" +
	"\t_is_valid\"p\n" +
	"\vGetResponse\x12a\n" +
	"\rvariant_price\x18\x01 \x01(\v2<.proto.product_service.variant.variant_price.v1.VariantPriceR\fvariantPrice\"\x9e\x03\n" +
	"\vListRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\fR\x05uuids\x12#\n" +
	"\rproduct_uuids\x18\x02 \x03(\fR\fproductUuids\x12#\n" +
	"\rvariant_uuids\x18\x03 \x03(\fR\fvariantUuids\x12\x18\n" +
	"\amarkets\x18\x04 \x03(\tR\amarkets\x12\x1e\n" +
	"\n" +
	"currencies\x18\x05 \x03(\tR\n" +
	"currencies\x12\\\n" +
	"\asources\x18\x06 \x03(\x0e2B.proto.product_service.variant.variant_price.v1.VariantPriceSourceR\asources\x12\x1e\n" +
	"\border_by\x18\a \x01(\tH\x00R\aorderBy\x88\x01\x01\x12 \n" +
	"\torder_dir\x18\b \x01(\tH\x01R\borderDir\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\n" +
	" \x01(\tR\tpageTokenB\v\n" +
	"\t_order_byB\f\n" +
	"\n" +
	"_order_dir\"\x9b\x01\n" +
	"\fListResponse\x12c\n" +
	"\x0evariant_prices\x18\x01 \x03(\v2<.proto.product_service.variant.variant_price.v1.VariantPriceR\rvariantPrices\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa8\x03\n" +
	"\x15ListIrrelevantRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\fR\x05uuids\x12#\n" +
	"\rproduct_uuids\x18\x02 \x03(\fR\fproductUuids\x12#\n" +
	"\rvariant_uuids\x18\x03 \x03(\fR\fvariantUuids\x12\x18\n" +
	"\amarkets\x18\x04 \x03(\tR\amarkets\x12\x1e\n" +
	"\n" +
	"currencies\x18\x05 \x03(\tR\n" +
	"currencies\x12\\\n" +
	"\asources\x18\x06 \x03(\x0e2B.proto.product_service.variant.variant_price.v1.VariantPriceSourceR\asources\x12\x1e\n" +
	"\border_by\x18\a \x01(\tH\x00R\aorderBy\x88\x01\x01\x12 \n" +
	"\torder_dir\x18\b \x01(\tH\x01R\borderDir\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\n" +
	" \x01(\tR\tpageTokenB\v\n" +
	"\t_order_byB\f\n" +
	"\n" +
	"_order_dir\"\xa5\x01\n" +
	"\x16ListIrrelevantResponse\x12c\n" +
	"\x0evariant_prices\x18\x01 \x03(\v2<.proto.product_service.variant.variant_price.v1.VariantPriceR\rvariantPrices\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xdb\x01\n" +
	"\rCreateRequest\x12!\n" +
	"\fvariant_uuid\x18\x01 \x01(\fR\vvariantUuid\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x05 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x06 \x01(\tR\tadminName\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\"s\n" +
	"\x0eCreateResponse\x12a\n" +
	"\rvariant_price\x18\x01 \x01(\v2<.proto.product_service.variant.variant_price.v1.VariantPriceR\fvariantPrice\"y\n" +
	"\x11InvalidateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x02 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x03 \x01(\tR\tadminName\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"\x14\n" +
	"\x12InvalidateResponse\"\r\n" +
	"\vPingRequest\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp*\xa8\x01\n" +
	"\x12VariantPriceSource\x12$\n" +
	" VARIANT_PRICE_SOURCE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVARIANT_PRICE_SOURCE_MANUAL\x10\x01\x12\"\n" +
	"\x1eVARIANT_PRICE_SOURCE_PROMOTION\x10\x02\x12'\n" +
	"#VARIANT_PRICE_SOURCE_AUTO_CONVERTED\x10\x032\xdf\x06\n" +
	"\x13VariantPriceService\x12\x81\x01\n" +
	"\x04Ping\x12;.proto.product_service.variant.variant_price.v1.PingRequest\x1a<.proto.product_service.variant.variant_price.v1.PingResponse\x12~\n" +
	"\x03Get\x12:.proto.product_service.variant.variant_price.v1.GetRequest\x1a;.proto.product_service.variant.variant_price.v1.GetResponse\x12\x81\x01\n" +
	"\x04List\x12;.proto.product_service.variant.variant_price.v1.ListRequest\x1a<.proto.product_service.variant.variant_price.v1.ListResponse\x12\x9f\x01\n" +
	"\x0eListIrrelevant\x12E.proto.product_service.variant.variant_price.v1.ListIrrelevantRequest\x1aF.proto.product_service.variant.variant_price.v1.ListIrrelevantResponse\x12\x87\x01\n" +
	"\x06Create\x12=.proto.product_service.variant.variant_price.v1.CreateRequest\x1a>.proto.product_service.variant.variant_price.v1.CreateResponse\x12\x93\x01\n" +
	"\n" +
	"Invalidate\x12A.proto.product_service.variant.variant_price.v1.InvalidateRequest\x1aB.proto.product_service.variant.variant_price.v1.InvalidateResponseBaZ_github.com/mikhail5545/protos/gen/go/product_service/variant/variant_price/v1;variant_pricepbv1b\x06proto3"

var (
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescOnce sync.Once
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescData []byte
)

func file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescGZIP() []byte {
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescOnce.Do(func() {
		file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDesc), len(file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDesc)))
	})
	return file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDescData
}

var file_proto_product_service_variant_variant_price_v1_variant_price_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_product_service_variant_variant_price_v1_variant_price_proto_goTypes = []any{
	(VariantPriceSource)(0),        // 0: proto.product_service.variant.variant_price.v1.VariantPriceSource
	(*VariantPrice)(nil),           // 1: proto.product_service.variant.variant_price.v1.VariantPrice
	(*GetRequest)(nil),             // 2: proto.product_service.variant.variant_price.v1.GetRequest
	(*GetResponse)(nil),            // 3: proto.product_service.variant.variant_price.v1.GetResponse
	(*ListRequest)(nil),            // 4: proto.product_service.variant.variant_price.v1.ListRequest
	(*ListResponse)(nil),           // 5: proto.product_service.variant.variant_price.v1.ListResponse
	(*ListIrrelevantRequest)(nil),  // 6: proto.product_service.variant.variant_price.v1.ListIrrelevantRequest
	(*ListIrrelevantResponse)(nil), // 7: proto.product_service.variant.variant_price.v1.ListIrrelevantResponse
	(*CreateRequest)(nil),          // 8: proto.product_service.variant.variant_price.v1.CreateRequest
	(*CreateResponse)(nil),         // 9: proto.product_service.variant.variant_price.v1.CreateResponse
	(*InvalidateRequest)(nil),      // 10: proto.product_service.variant.variant_price.v1.InvalidateRequest
	(*InvalidateResponse)(nil),     // 11: proto.product_service.variant.variant_price.v1.InvalidateResponse
	(*PingRequest)(nil),            // 12: proto.product_service.variant.variant_price.v1.PingRequest
	(*PingResponse)(nil),           // 13: proto.product_service.variant.variant_price.v1.PingResponse
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_proto_product_service_variant_variant_price_v1_variant_price_proto_depIdxs = []int32{
	14, // 0: proto.product_service.variant.variant_price.v1.VariantPrice.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: proto.product_service.variant.variant_price.v1.VariantPrice.updated_at:type_name -> google.protobuf.Timestamp
	14, // 2: proto.product_service.variant.variant_price.v1.VariantPrice.valid_from:type_name -> google.protobuf.Timestamp
	14, // 3: proto.product_service.variant.variant_price.v1.VariantPrice.valid_to:type_name -> google.protobuf.Timestamp
	0,  // 4: proto.product_service.variant.variant_price.v1.VariantPrice.source:type_name -> proto.product_service.variant.variant_price.v1.VariantPriceSource
	1,  // 5: proto.product_service.variant.variant_price.v1.GetResponse.variant_price:type_name -> proto.product_service.variant.variant_price.v1.VariantPrice
	0,  // 6: proto.product_service.variant.variant_price.v1.ListRequest.sources:type_name -> proto.product_service.variant.variant_price.v1.VariantPriceSource
	1,  // 7: proto.product_service.variant.variant_price.v1.ListResponse.variant_prices:type_name -> proto.product_service.variant.variant_price.v1.VariantPrice
	0,  // 8: proto.product_service.variant.variant_price.v1.ListIrrelevantRequest.sources:type_name -> proto.product_service.variant.variant_price.v1.VariantPriceSource
	1,  // 9: proto.product_service.variant.variant_price.v1.ListIrrelevantResponse.variant_prices:type_name -> proto.product_service.variant.variant_price.v1.VariantPrice
	1,  // 10: proto.product_service.variant.variant_price.v1.CreateResponse.variant_price:type_name -> proto.product_service.variant.variant_price.v1.VariantPrice
	12, // 11: proto.product_service.variant.variant_price.v1.VariantPriceService.Ping:input_type -> proto.product_service.variant.variant_price.v1.PingRequest
	2,  // 12: proto.product_service.variant.variant_price.v1.VariantPriceService.Get:input_type -> proto.product_service.variant.variant_price.v1.GetRequest
	4,  // 13: proto.product_service.variant.variant_price.v1.VariantPriceService.List:input_type -> proto.product_service.variant.variant_price.v1.ListRequest
	6,  // 14: proto.product_service.variant.variant_price.v1.VariantPriceService.ListIrrelevant:input_type -> proto.product_service.variant.variant_price.v1.ListIrrelevantRequest
	8,  // 15: proto.product_service.variant.variant_price.v1.VariantPriceService.Create:input_type -> proto.product_service.variant.variant_price.v1.CreateRequest
	10, // 16: proto.product_service.variant.variant_price.v1.VariantPriceService.Invalidate:input_type -> proto.product_service.variant.variant_price.v1.InvalidateRequest
	13, // 17: proto.product_service.variant.variant_price.v1.VariantPriceService.Ping:output_type -> proto.product_service.variant.variant_price.v1.PingResponse
	3,  // 18: proto.product_service.variant.variant_price.v1.VariantPriceService.Get:output_type -> proto.product_service.variant.variant_price.v1.GetResponse
	5,  // 19: proto.product_service.variant.variant_price.v1.VariantPriceService.List:output_type -> proto.product_service.variant.variant_price.v1.ListResponse
	7,  // 20: proto.product_service.variant.variant_price.v1.VariantPriceService.ListIrrelevant:output_type -> proto.product_service.variant.variant_price.v1.ListIrrelevantResponse
	9,  // 21: proto.product_service.variant.variant_price.v1.VariantPriceService.Create:output_type -> proto.product_service.variant.variant_price.v1.CreateResponse
	11, // 22: proto.product_service.variant.variant_price.v1.VariantPriceService.Invalidate:output_type -> proto.product_service.variant.variant_price.v1.InvalidateResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_product_service_variant_variant_price_v1_variant_price_proto_init() }
func file_proto_product_service_variant_variant_price_v1_variant_price_proto_init() {
	if File_proto_product_service_variant_variant_price_v1_variant_price_proto != nil {
		return
	}
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDesc), len(file_proto_product_service_variant_variant_price_v1_variant_price_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_service_variant_variant_price_v1_variant_price_proto_goTypes,
		DependencyIndexes: file_proto_product_service_variant_variant_price_v1_variant_price_proto_depIdxs,
		EnumInfos:         file_proto_product_service_variant_variant_price_v1_variant_price_proto_enumTypes,
		MessageInfos:      file_proto_product_service_variant_variant_price_v1_variant_price_proto_msgTypes,
	}.Build()
	File_proto_product_service_variant_variant_price_v1_variant_price_proto = out.File
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_goTypes = nil
	file_proto_product_service_variant_variant_price_v1_variant_price_proto_depIdxs = nil
}
