// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/product_service/digital/v1/digital.proto

package digitalpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_UNSPECIFIED AssetStatus = 0
	AssetStatus_ASSET_STATUS_DRAFT       AssetStatus = 1
	AssetStatus_ASSET_STATUS_PUBLISHED   AssetStatus = 2
	AssetStatus_ASSET_STATUS_ARCHIVED    AssetStatus = 3
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_UNSPECIFIED",
		1: "ASSET_STATUS_DRAFT",
		2: "ASSET_STATUS_PUBLISHED",
		3: "ASSET_STATUS_ARCHIVED",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_UNSPECIFIED": 0,
		"ASSET_STATUS_DRAFT":       1,
		"ASSET_STATUS_PUBLISHED":   2,
		"ASSET_STATUS_ARCHIVED":    3,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_service_digital_v1_digital_proto_enumTypes[0].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_proto_product_service_digital_v1_digital_proto_enumTypes[0]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{0}
}

type Asset struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uuid               []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	VariantUuid        []byte                 `protobuf:"bytes,5,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	LessonUuid         []byte                 `protobuf:"bytes,6,opt,name=lesson_uuid,json=lessonUuid,proto3,oneof" json:"lesson_uuid,omitempty"`
	FileName           string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize           int64                  `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	CloudinaryPublicId string                 `protobuf:"bytes,9,opt,name=cloudinary_public_id,json=cloudinaryPublicId,proto3" json:"cloudinary_public_id,omitempty"`
	FileUrl            string                 `protobuf:"bytes,10,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSecureUrl      string                 `protobuf:"bytes,11,opt,name=file_secure_url,json=fileSecureUrl,proto3" json:"file_secure_url,omitempty"`
	MediaServiceId     []byte                 `protobuf:"bytes,12,opt,name=media_service_id,json=mediaServiceId,proto3" json:"media_service_id,omitempty"`
	MimeType           string                 `protobuf:"bytes,13,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Status             AssetStatus            `protobuf:"varint,14,opt,name=status,proto3,enum=proto.product_service.digital.v1.AssetStatus" json:"status,omitempty"`
	Note               *string                `protobuf:"bytes,15,opt,name=note,proto3,oneof" json:"note,omitempty"`
	ArchiveReason      *string                `protobuf:"bytes,16,opt,name=archive_reason,json=archiveReason,proto3,oneof" json:"archive_reason,omitempty"`
	CreatedBy          []byte                 `protobuf:"bytes,17,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	PublishedBy        []byte                 `protobuf:"bytes,18,opt,name=published_by,json=publishedBy,proto3,oneof" json:"published_by,omitempty"`
	ArchivedBy         []byte                 `protobuf:"bytes,19,opt,name=archived_by,json=archivedBy,proto3,oneof" json:"archived_by,omitempty"`
	CreatedByName      *string                `protobuf:"bytes,20,opt,name=created_by_name,json=createdByName,proto3,oneof" json:"created_by_name,omitempty"`
	PublishedByName    *string                `protobuf:"bytes,21,opt,name=published_by_name,json=publishedByName,proto3,oneof" json:"published_by_name,omitempty"`
	ArchivedByName     *string                `protobuf:"bytes,22,opt,name=archived_by_name,json=archivedByName,proto3,oneof" json:"archived_by_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Asset) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Asset) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *Asset) GetLessonUuid() []byte {
	if x != nil {
		return x.LessonUuid
	}
	return nil
}

func (x *Asset) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Asset) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Asset) GetCloudinaryPublicId() string {
	if x != nil {
		return x.CloudinaryPublicId
	}
	return ""
}

func (x *Asset) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Asset) GetFileSecureUrl() string {
	if x != nil {
		return x.FileSecureUrl
	}
	return ""
}

func (x *Asset) GetMediaServiceId() []byte {
	if x != nil {
		return x.MediaServiceId
	}
	return nil
}

func (x *Asset) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Asset) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_UNSPECIFIED
}

func (x *Asset) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *Asset) GetArchiveReason() string {
	if x != nil && x.ArchiveReason != nil {
		return *x.ArchiveReason
	}
	return ""
}

func (x *Asset) GetCreatedBy() []byte {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Asset) GetPublishedBy() []byte {
	if x != nil {
		return x.PublishedBy
	}
	return nil
}

func (x *Asset) GetArchivedBy() []byte {
	if x != nil {
		return x.ArchivedBy
	}
	return nil
}

func (x *Asset) GetCreatedByName() string {
	if x != nil && x.CreatedByName != nil {
		return *x.CreatedByName
	}
	return ""
}

func (x *Asset) GetPublishedByName() string {
	if x != nil && x.PublishedByName != nil {
		return *x.PublishedByName
	}
	return ""
}

func (x *Asset) GetArchivedByName() string {
	if x != nil && x.ArchivedByName != nil {
		return *x.ArchivedByName
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetWithDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithDraftRequest) Reset() {
	*x = GetWithDraftRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithDraftRequest) ProtoMessage() {}

func (x *GetWithDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithDraftRequest.ProtoReflect.Descriptor instead.
func (*GetWithDraftRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{3}
}

func (x *GetWithDraftRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type GetWithDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithDraftResponse) Reset() {
	*x = GetWithDraftResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithDraftResponse) ProtoMessage() {}

func (x *GetWithDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithDraftResponse.ProtoReflect.Descriptor instead.
func (*GetWithDraftResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{4}
}

func (x *GetWithDraftResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetWithArchivedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithArchivedRequest) Reset() {
	*x = GetWithArchivedRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithArchivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithArchivedRequest) ProtoMessage() {}

func (x *GetWithArchivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithArchivedRequest.ProtoReflect.Descriptor instead.
func (*GetWithArchivedRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{5}
}

func (x *GetWithArchivedRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type GetWithArchivedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithArchivedResponse) Reset() {
	*x = GetWithArchivedResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithArchivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithArchivedResponse) ProtoMessage() {}

func (x *GetWithArchivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithArchivedResponse.ProtoReflect.Descriptor instead.
func (*GetWithArchivedResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{6}
}

func (x *GetWithArchivedResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type ListRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuids             [][]byte               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	MediaServiceUuids [][]byte               `protobuf:"bytes,2,rep,name=media_service_uuids,json=mediaServiceUuids,proto3" json:"media_service_uuids,omitempty"`
	VariantUuids      [][]byte               `protobuf:"bytes,3,rep,name=variant_uuids,json=variantUuids,proto3" json:"variant_uuids,omitempty"`
	LessonUuids       [][]byte               `protobuf:"bytes,4,rep,name=lesson_uuids,json=lessonUuids,proto3" json:"lesson_uuids,omitempty"`
	MimeTypes         []string               `protobuf:"bytes,5,rep,name=mime_types,json=mimeTypes,proto3" json:"mime_types,omitempty"`
	OrderBy           *string                `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDir          *string                `protobuf:"bytes,7,opt,name=order_dir,json=orderDir,proto3,oneof" json:"order_dir,omitempty"`
	PageSize          int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,9,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{7}
}

func (x *ListRequest) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *ListRequest) GetMediaServiceUuids() [][]byte {
	if x != nil {
		return x.MediaServiceUuids
	}
	return nil
}

func (x *ListRequest) GetVariantUuids() [][]byte {
	if x != nil {
		return x.VariantUuids
	}
	return nil
}

func (x *ListRequest) GetLessonUuids() [][]byte {
	if x != nil {
		return x.LessonUuids
	}
	return nil
}

func (x *ListRequest) GetMimeTypes() []string {
	if x != nil {
		return x.MimeTypes
	}
	return nil
}

func (x *ListRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListRequest) GetOrderDir() string {
	if x != nil && x.OrderDir != nil {
		return *x.OrderDir
	}
	return ""
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListDraftsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuids             [][]byte               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	MediaServiceUuids [][]byte               `protobuf:"bytes,2,rep,name=media_service_uuids,json=mediaServiceUuids,proto3" json:"media_service_uuids,omitempty"`
	VariantUuids      [][]byte               `protobuf:"bytes,3,rep,name=variant_uuids,json=variantUuids,proto3" json:"variant_uuids,omitempty"`
	LessonUuids       [][]byte               `protobuf:"bytes,4,rep,name=lesson_uuids,json=lessonUuids,proto3" json:"lesson_uuids,omitempty"`
	MimeTypes         []string               `protobuf:"bytes,5,rep,name=mime_types,json=mimeTypes,proto3" json:"mime_types,omitempty"`
	OrderBy           *string                `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDir          *string                `protobuf:"bytes,7,opt,name=order_dir,json=orderDir,proto3,oneof" json:"order_dir,omitempty"`
	PageSize          int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,9,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListDraftsRequest) Reset() {
	*x = ListDraftsRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsRequest) ProtoMessage() {}

func (x *ListDraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsRequest.ProtoReflect.Descriptor instead.
func (*ListDraftsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{9}
}

func (x *ListDraftsRequest) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *ListDraftsRequest) GetMediaServiceUuids() [][]byte {
	if x != nil {
		return x.MediaServiceUuids
	}
	return nil
}

func (x *ListDraftsRequest) GetVariantUuids() [][]byte {
	if x != nil {
		return x.VariantUuids
	}
	return nil
}

func (x *ListDraftsRequest) GetLessonUuids() [][]byte {
	if x != nil {
		return x.LessonUuids
	}
	return nil
}

func (x *ListDraftsRequest) GetMimeTypes() []string {
	if x != nil {
		return x.MimeTypes
	}
	return nil
}

func (x *ListDraftsRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListDraftsRequest) GetOrderDir() string {
	if x != nil && x.OrderDir != nil {
		return *x.OrderDir
	}
	return ""
}

func (x *ListDraftsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDraftsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListDraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDraftsResponse) Reset() {
	*x = ListDraftsResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsResponse) ProtoMessage() {}

func (x *ListDraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsResponse.ProtoReflect.Descriptor instead.
func (*ListDraftsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{10}
}

func (x *ListDraftsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListDraftsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListArchivedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuids             [][]byte               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	MediaServiceUuids [][]byte               `protobuf:"bytes,2,rep,name=media_service_uuids,json=mediaServiceUuids,proto3" json:"media_service_uuids,omitempty"`
	VariantUuids      [][]byte               `protobuf:"bytes,3,rep,name=variant_uuids,json=variantUuids,proto3" json:"variant_uuids,omitempty"`
	LessonUuids       [][]byte               `protobuf:"bytes,4,rep,name=lesson_uuids,json=lessonUuids,proto3" json:"lesson_uuids,omitempty"`
	MimeTypes         []string               `protobuf:"bytes,5,rep,name=mime_types,json=mimeTypes,proto3" json:"mime_types,omitempty"`
	OrderBy           *string                `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDir          *string                `protobuf:"bytes,7,opt,name=order_dir,json=orderDir,proto3,oneof" json:"order_dir,omitempty"`
	PageSize          int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                 `protobuf:"bytes,9,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListArchivedRequest) Reset() {
	*x = ListArchivedRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArchivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchivedRequest) ProtoMessage() {}

func (x *ListArchivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchivedRequest.ProtoReflect.Descriptor instead.
func (*ListArchivedRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{11}
}

func (x *ListArchivedRequest) GetUuids() [][]byte {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *ListArchivedRequest) GetMediaServiceUuids() [][]byte {
	if x != nil {
		return x.MediaServiceUuids
	}
	return nil
}

func (x *ListArchivedRequest) GetVariantUuids() [][]byte {
	if x != nil {
		return x.VariantUuids
	}
	return nil
}

func (x *ListArchivedRequest) GetLessonUuids() [][]byte {
	if x != nil {
		return x.LessonUuids
	}
	return nil
}

func (x *ListArchivedRequest) GetMimeTypes() []string {
	if x != nil {
		return x.MimeTypes
	}
	return nil
}

func (x *ListArchivedRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListArchivedRequest) GetOrderDir() string {
	if x != nil && x.OrderDir != nil {
		return *x.OrderDir
	}
	return ""
}

func (x *ListArchivedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArchivedRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListArchivedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArchivedResponse) Reset() {
	*x = ListArchivedResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArchivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchivedResponse) ProtoMessage() {}

func (x *ListArchivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchivedResponse.ProtoReflect.Descriptor instead.
func (*ListArchivedResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{12}
}

func (x *ListArchivedResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListArchivedResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VariantUuid        []byte                 `protobuf:"bytes,1,opt,name=variant_uuid,json=variantUuid,proto3" json:"variant_uuid,omitempty"`
	FileName           string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize           int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	CloudinaryPublicId string                 `protobuf:"bytes,4,opt,name=cloudinary_public_id,json=cloudinaryPublicId,proto3" json:"cloudinary_public_id,omitempty"`
	FileUrl            string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSecureUrl      string                 `protobuf:"bytes,6,opt,name=file_secure_url,json=fileSecureUrl,proto3" json:"file_secure_url,omitempty"`
	MediaServiceId     []byte                 `protobuf:"bytes,7,opt,name=media_service_id,json=mediaServiceId,proto3" json:"media_service_id,omitempty"`
	MimeType           string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRequest) GetVariantUuid() []byte {
	if x != nil {
		return x.VariantUuid
	}
	return nil
}

func (x *CreateRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CreateRequest) GetCloudinaryPublicId() string {
	if x != nil {
		return x.CloudinaryPublicId
	}
	return ""
}

func (x *CreateRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *CreateRequest) GetFileSecureUrl() string {
	if x != nil {
		return x.FileSecureUrl
	}
	return ""
}

func (x *CreateRequest) GetMediaServiceId() []byte {
	if x != nil {
		return x.MediaServiceId
	}
	return nil
}

func (x *CreateRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{14}
}

func (x *CreateResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type UpdateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uuid               []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FileName           *string                `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	FileSize           *int64                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3,oneof" json:"file_size,omitempty"`
	CloudinaryPublicId *string                `protobuf:"bytes,4,opt,name=cloudinary_public_id,json=cloudinaryPublicId,proto3,oneof" json:"cloudinary_public_id,omitempty"`
	FileUrl            *string                `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3,oneof" json:"file_url,omitempty"`
	FileSecureUrl      *string                `protobuf:"bytes,6,opt,name=file_secure_url,json=fileSecureUrl,proto3,oneof" json:"file_secure_url,omitempty"`
	MimeType           *string                `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	Updates            *fieldmaskpb.FieldMask `protobuf:"bytes,8,opt,name=updates,proto3" json:"updates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateRequest) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *UpdateRequest) GetFileSize() int64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *UpdateRequest) GetCloudinaryPublicId() string {
	if x != nil && x.CloudinaryPublicId != nil {
		return *x.CloudinaryPublicId
	}
	return ""
}

func (x *UpdateRequest) GetFileUrl() string {
	if x != nil && x.FileUrl != nil {
		return *x.FileUrl
	}
	return ""
}

func (x *UpdateRequest) GetFileSecureUrl() string {
	if x != nil && x.FileSecureUrl != nil {
		return *x.FileSecureUrl
	}
	return ""
}

func (x *UpdateRequest) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *UpdateRequest) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uuid               []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FileName           *string                `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	FileSize           *int64                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3,oneof" json:"file_size,omitempty"`
	CloudinaryPublicId *string                `protobuf:"bytes,4,opt,name=cloudinary_public_id,json=cloudinaryPublicId,proto3,oneof" json:"cloudinary_public_id,omitempty"`
	FileUrl            *string                `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3,oneof" json:"file_url,omitempty"`
	FileSecureUrl      *string                `protobuf:"bytes,6,opt,name=file_secure_url,json=fileSecureUrl,proto3,oneof" json:"file_secure_url,omitempty"`
	MimeType           *string                `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	Updates            *fieldmaskpb.FieldMask `protobuf:"bytes,8,opt,name=updates,proto3" json:"updates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateResponse) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *UpdateResponse) GetFileSize() int64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *UpdateResponse) GetCloudinaryPublicId() string {
	if x != nil && x.CloudinaryPublicId != nil {
		return *x.CloudinaryPublicId
	}
	return ""
}

func (x *UpdateResponse) GetFileUrl() string {
	if x != nil && x.FileUrl != nil {
		return *x.FileUrl
	}
	return ""
}

func (x *UpdateResponse) GetFileSecureUrl() string {
	if x != nil && x.FileSecureUrl != nil {
		return *x.FileSecureUrl
	}
	return ""
}

func (x *UpdateResponse) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *UpdateResponse) GetUpdates() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Updates
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Note          *string                `protobuf:"bytes,2,opt,name=note,proto3,oneof" json:"note,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,3,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,4,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{17}
}

func (x *PublishRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *PublishRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *PublishRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *PublishRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{18}
}

type ArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Note          *string                `protobuf:"bytes,2,opt,name=note,proto3,oneof" json:"note,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,3,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,4,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRequest) Reset() {
	*x = ArchiveRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRequest) ProtoMessage() {}

func (x *ArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{19}
}

func (x *ArchiveRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ArchiveRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *ArchiveRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *ArchiveRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type ArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveResponse) Reset() {
	*x = ArchiveResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveResponse) ProtoMessage() {}

func (x *ArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveResponse.ProtoReflect.Descriptor instead.
func (*ArchiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{20}
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Note          *string                `protobuf:"bytes,2,opt,name=note,proto3,oneof" json:"note,omitempty"`
	AdminUuid     []byte                 `protobuf:"bytes,3,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName     string                 `protobuf:"bytes,4,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{21}
}

func (x *RestoreRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *RestoreRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *RestoreRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *RestoreRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{22}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{23}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_service_digital_v1_digital_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_service_digital_v1_digital_proto_rawDescGZIP(), []int{24}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_product_service_digital_v1_digital_proto protoreflect.FileDescriptor

const file_proto_product_service_digital_v1_digital_proto_rawDesc = "" +
	"\n" +
	".proto/product_service/digital/v1/digital.proto\x12 proto.product_service.digital.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xc5\b\n" +
	"\x05Asset\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12!\n" +
	"\fvariant_uuid\x18\x05 \x01(\fR\vvariantUuid\x12$\n" +
	"\vlesson_uuid\x18\x06 \x01(\fH\x01R\n" +
	"lessonUuid\x88\x01\x01\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\b \x01(\x03R\bfileSize\x120\n" +
	"\x14cloudinary_public_id\x18\t \x01(\tR\x12cloudinaryPublicId\x12\x19\n" +
	"\bfile_url\x18\n" +
	" \x01(\tR\afileUrl\x12&\n" +
	"\x0ffile_secure_url\x18\v \x01(\tR\rfileSecureUrl\x12(\n" +
	"\x10media_service_id\x18\f \x01(\fR\x0emediaServiceId\x12\x1b\n" +
	"\tmime_type\x18\r \x01(\tR\bmimeType\x12E\n" +
	"\x06status\x18\x0e \x01(\x0e2-.proto.product_service.digital.v1.AssetStatusR\x06status\x12\x17\n" +
	"\x04note\x18\x0f \x01(\tH\x02R\x04note\x88\x01\x01\x12*\n" +
	"\x0earchive_reason\x18\x10 \x01(\tH\x03R\rarchiveReason\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x11 \x01(\fH\x04R\tcreatedBy\x88\x01\x01\x12&\n" +
	"\fpublished_by\x18\x12 \x01(\fH\x05R\vpublishedBy\x88\x01\x01\x12$\n" +
	"\varchived_by\x18\x13 \x01(\fH\x06R\n" +
	"archivedBy\x88\x01\x01\x12+\n" +
	"\x0fcreated_by_name\x18\x14 \x01(\tH\aR\rcreatedByName\x88\x01\x01\x12/\n" +
	"\x11published_by_name\x18\x15 \x01(\tH\bR\x0fpublishedByName\x88\x01\x01\x12-\n" +
	"\x10archived_by_name\x18\x16 \x01(\tH\tR\x0earchivedByName\x88\x01\x01B\r\n" +
	"\v_deleted_atB\x0e\n" +
	"\f_lesson_uuidB\a\n" +
	"\x05_noteB\x11\n" +
	"\x0f_archive_reasonB\r\n" +
	"\v_created_byB\x0f\n" +
	"\r_published_byB\x0e\n" +
	"\f_archived_byB\x12\n" +
	"\x10_created_by_nameB\x14\n" +
	"\x12_published_by_nameB\x13\n" +
	"\x11_archived_by_name\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"L\n" +
	"\vGetResponse\x12=\n" +
	"\x05asset\x18\x01 \x01(\v2'.proto.product_service.digital.v1.AssetR\x05asset\")\n" +
	"\x13GetWithDraftRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"U\n" +
	"\x14GetWithDraftResponse\x12=\n" +
	"\x05asset\x18\x01 \x01(\v2'.proto.product_service.digital.v1.AssetR\x05asset\",\n" +
	"\x16GetWithArchivedRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"X\n" +
	"\x17GetWithArchivedResponse\x12=\n" +
	"\x05asset\x18\x01 \x01(\v2'.proto.product_service.digital.v1.AssetR\x05asset\"\xd3\x02\n" +
	"\vListRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\fR\x05uuids\x12.\n" +
	"\x13media_service_uuids\x18\x02 \x03(\fR\x11mediaServiceUuids\x12#\n" +
	"\rvariant_uuids\x18\x03 \x03(\fR\fvariantUuids\x12!\n" +
	"\flesson_uuids\x18\x04 \x03(\fR\vlessonUuids\x12\x1d\n" +
	"\n" +
	"mime_types\x18\x05 \x03(\tR\tmimeTypes\x12\x1e\n" +
	"\border_by\x18\x06 \x01(\tH\x00R\aorderBy\x88\x01\x01\x12 \n" +
	"\torder_dir\x18\a \x01(\tH\x01R\borderDir\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\t \x01(\tR\tpageTokenB\v\n" +
	"\t_order_byB\f\n" +
	"\n" +
	"_order_dir\"w\n" +
	"\fListResponse\x12?\n" +
	"\x06assets\x18\x01 \x03(\v2'.proto.product_service.digital.v1.AssetR\x06assets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd9\x02\n" +
	"\x11ListDraftsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\fR\x05uuids\x12.\n" +
	"\x13media_service_uuids\x18\x02 \x03(\fR\x11mediaServiceUuids\x12#\n" +
	"\rvariant_uuids\x18\x03 \x03(\fR\fvariantUuids\x12!\n" +
	"\flesson_uuids\x18\x04 \x03(\fR\vlessonUuids\x12\x1d\n" +
	"\n" +
	"mime_types\x18\x05 \x03(\tR\tmimeTypes\x12\x1e\n" +
	"\border_by\x18\x06 \x01(\tH\x00R\aorderBy\x88\x01\x01\x12 \n" +
	"\torder_dir\x18\a \x01(\tH\x01R\borderDir\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\t \x01(\tR\tpageTokenB\v\n" +
	"\t_order_byB\f\n" +
	"\n" +
	"_order_dir\"}\n" +
	"\x12ListDraftsResponse\x12?\n" +
	"\x06assets\x18\x01 \x03(\v2'.proto.product_service.digital.v1.AssetR\x06assets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xdb\x02\n" +
	"\x13ListArchivedRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\fR\x05uuids\x12.\n" +
	"\x13media_service_uuids\x18\x02 \x03(\fR\x11mediaServiceUuids\x12#\n" +
	"\rvariant_uuids\x18\x03 \x03(\fR\fvariantUuids\x12!\n" +
	"\flesson_uuids\x18\x04 \x03(\fR\vlessonUuids\x12\x1d\n" +
	"\n" +
	"mime_types\x18\x05 \x03(\tR\tmimeTypes\x12\x1e\n" +
	"\border_by\x18\x06 \x01(\tH\x00R\aorderBy\x88\x01\x01\x12 \n" +
	"\torder_dir\x18\a \x01(\tH\x01R\borderDir\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\t \x01(\tR\tpageTokenB\v\n" +
	"\t_order_byB\f\n" +
	"\n" +
	"_order_dir\"\x7f\n" +
	"\x14ListArchivedResponse\x12?\n" +
	"\x06assets\x18\x01 \x03(\v2'.proto.product_service.digital.v1.AssetR\x06assets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa8\x02\n" +
	"\rCreateRequest\x12!\n" +
	"\fvariant_uuid\x18\x01 \x01(\fR\vvariantUuid\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x120\n" +
	"\x14cloudinary_public_id\x18\x04 \x01(\tR\x12cloudinaryPublicId\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12&\n" +
	"\x0ffile_secure_url\x18\x06 \x01(\tR\rfileSecureUrl\x12(\n" +
	"\x10media_service_id\x18\a \x01(\fR\x0emediaServiceId\x12\x1b\n" +
	"\tmime_type\x18\b \x01(\tR\bmimeType\"O\n" +
	"\x0eCreateResponse\x12=\n" +
	"\x05asset\x18\x01 \x01(\v2'.proto.product_service.digital.v1.AssetR\x05asset\"\xa7\x03\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12 \n" +
	"\tfile_name\x18\x02 \x01(\tH\x00R\bfileName\x88\x01\x01\x12 \n" +
	"\tfile_size\x18\x03 \x01(\x03H\x01R\bfileSize\x88\x01\x01\x125\n" +
	"\x14cloudinary_public_id\x18\x04 \x01(\tH\x02R\x12cloudinaryPublicId\x88\x01\x01\x12\x1e\n" +
	"\bfile_url\x18\x05 \x01(\tH\x03R\afileUrl\x88\x01\x01\x12+\n" +
	"\x0ffile_secure_url\x18\x06 \x01(\tH\x04R\rfileSecureUrl\x88\x01\x01\x12 \n" +
	"\tmime_type\x18\a \x01(\tH\x05R\bmimeType\x88\x01\x01\x124\n" +
	"\aupdates\x18\b \x01(\v2\x1a.google.protobuf.FieldMaskR\aupdatesB\f\n" +
	"\n" +
	"_file_nameB\f\n" +
	"\n" +
	"_file_sizeB\x17\n" +
	"\x15_cloudinary_public_idB\v\n" +
	"\t_file_urlB\x12\n" +
	"\x10_file_secure_urlB\f\n" +
	"\n" +
	"_mime_type\"\xa8\x03\n" +
	"\x0eUpdateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12 \n" +
	"\tfile_name\x18\x02 \x01(\tH\x00R\bfileName\x88\x01\x01\x12 \n" +
	"\tfile_size\x18\x03 \x01(\x03H\x01R\bfileSize\x88\x01\x01\x125\n" +
	"\x14cloudinary_public_id\x18\x04 \x01(\tH\x02R\x12cloudinaryPublicId\x88\x01\x01\x12\x1e\n" +
	"\bfile_url\x18\x05 \x01(\tH\x03R\afileUrl\x88\x01\x01\x12+\n" +
	"\x0ffile_secure_url\x18\x06 \x01(\tH\x04R\rfileSecureUrl\x88\x01\x01\x12 \n" +
	"\tmime_type\x18\a \x01(\tH\x05R\bmimeType\x88\x01\x01\x124\n" +
	"\aupdates\x18\b \x01(\v2\x1a.google.protobuf.FieldMaskR\aupdatesB\f\n" +
	"\n" +
	"_file_nameB\f\n" +
	"\n" +
	"_file_sizeB\x17\n" +
	"\x15_cloudinary_public_idB\v\n" +
	"\t_file_urlB\x12\n" +
	"\x10_file_secure_urlB\f\n" +
	"\n" +
	"_mime_type\"\x84\x01\n" +
	"\x0ePublishRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x17\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04note\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x03 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x04 \x01(\tR\tadminNameB\a\n" +
	"\x05_note\"\x11\n" +
	"\x0fPublishResponse\"\x84\x01\n" +
	"\x0eArchiveRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x17\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04note\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x03 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x04 \x01(\tR\tadminNameB\a\n" +
	"\x05_note\"\x11\n" +
	"\x0fArchiveResponse\"\x84\x01\n" +
	"\x0eRestoreRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x17\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04note\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x03 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x04 \x01(\tR\tadminNameB\a\n" +
	"\x05_note\"\x11\n" +
	"\x0fRestoreResponse\"\r\n" +
	"\vPingRequest\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp*z\n" +
	"\vAssetStatus\x12\x1c\n" +
	"\x18ASSET_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ASSET_STATUS_DRAFT\x10\x01\x12\x1a\n" +
	"\x16ASSET_STATUS_PUBLISHED\x10\x02\x12\x19\n" +
	"\x15ASSET_STATUS_ARCHIVED\x10\x032\xea\n" +
	"\n" +
	"\fAssetService\x12e\n" +
	"\x04Ping\x12-.proto.product_service.digital.v1.PingRequest\x1a..proto.product_service.digital.v1.PingResponse\x12b\n" +
	"\x03Get\x12,.proto.product_service.digital.v1.GetRequest\x1a-.proto.product_service.digital.v1.GetResponse\x12}\n" +
	"\fGetWithDraft\x125.proto.product_service.digital.v1.GetWithDraftRequest\x1a6.proto.product_service.digital.v1.GetWithDraftResponse\x12\x86\x01\n" +
	"\x0fGetWithArchived\x128.proto.product_service.digital.v1.GetWithArchivedRequest\x1a9.proto.product_service.digital.v1.GetWithArchivedResponse\x12e\n" +
	"\x04List\x12-.proto.product_service.digital.v1.ListRequest\x1a..proto.product_service.digital.v1.ListResponse\x12w\n" +
	"\n" +
	"ListDrafts\x123.proto.product_service.digital.v1.ListDraftsRequest\x1a4.proto.product_service.digital.v1.ListDraftsResponse\x12}\n" +
	"\fListArchived\x125.proto.product_service.digital.v1.ListArchivedRequest\x1a6.proto.product_service.digital.v1.ListArchivedResponse\x12k\n" +
	"\x06Create\x12/.proto.product_service.digital.v1.CreateRequest\x1a0.proto.product_service.digital.v1.CreateResponse\x12k\n" +
	"\x06Update\x12/.proto.product_service.digital.v1.UpdateRequest\x1a0.proto.product_service.digital.v1.UpdateResponse\x12n\n" +
	"\aPublish\x120.proto.product_service.digital.v1.PublishRequest\x1a1.proto.product_service.digital.v1.PublishResponse\x12n\n" +
	"\aArchive\x120.proto.product_service.digital.v1.ArchiveRequest\x1a1.proto.product_service.digital.v1.ArchiveResponse\x12n\n" +
	"\aRestore\x120.proto.product_service.digital.v1.RestoreRequest\x1a1.proto.product_service.digital.v1.RestoreResponseBMZKgithub.com/mikhail5545/protos/gen/go/product_service/digital/v1;digitalpbv1b\x06proto3"

var (
	file_proto_product_service_digital_v1_digital_proto_rawDescOnce sync.Once
	file_proto_product_service_digital_v1_digital_proto_rawDescData []byte
)

func file_proto_product_service_digital_v1_digital_proto_rawDescGZIP() []byte {
	file_proto_product_service_digital_v1_digital_proto_rawDescOnce.Do(func() {
		file_proto_product_service_digital_v1_digital_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_service_digital_v1_digital_proto_rawDesc), len(file_proto_product_service_digital_v1_digital_proto_rawDesc)))
	})
	return file_proto_product_service_digital_v1_digital_proto_rawDescData
}

var file_proto_product_service_digital_v1_digital_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_product_service_digital_v1_digital_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_product_service_digital_v1_digital_proto_goTypes = []any{
	(AssetStatus)(0),                // 0: proto.product_service.digital.v1.AssetStatus
	(*Asset)(nil),                   // 1: proto.product_service.digital.v1.Asset
	(*GetRequest)(nil),              // 2: proto.product_service.digital.v1.GetRequest
	(*GetResponse)(nil),             // 3: proto.product_service.digital.v1.GetResponse
	(*GetWithDraftRequest)(nil),     // 4: proto.product_service.digital.v1.GetWithDraftRequest
	(*GetWithDraftResponse)(nil),    // 5: proto.product_service.digital.v1.GetWithDraftResponse
	(*GetWithArchivedRequest)(nil),  // 6: proto.product_service.digital.v1.GetWithArchivedRequest
	(*GetWithArchivedResponse)(nil), // 7: proto.product_service.digital.v1.GetWithArchivedResponse
	(*ListRequest)(nil),             // 8: proto.product_service.digital.v1.ListRequest
	(*ListResponse)(nil),            // 9: proto.product_service.digital.v1.ListResponse
	(*ListDraftsRequest)(nil),       // 10: proto.product_service.digital.v1.ListDraftsRequest
	(*ListDraftsResponse)(nil),      // 11: proto.product_service.digital.v1.ListDraftsResponse
	(*ListArchivedRequest)(nil),     // 12: proto.product_service.digital.v1.ListArchivedRequest
	(*ListArchivedResponse)(nil),    // 13: proto.product_service.digital.v1.ListArchivedResponse
	(*CreateRequest)(nil),           // 14: proto.product_service.digital.v1.CreateRequest
	(*CreateResponse)(nil),          // 15: proto.product_service.digital.v1.CreateResponse
	(*UpdateRequest)(nil),           // 16: proto.product_service.digital.v1.UpdateRequest
	(*UpdateResponse)(nil),          // 17: proto.product_service.digital.v1.UpdateResponse
	(*PublishRequest)(nil),          // 18: proto.product_service.digital.v1.PublishRequest
	(*PublishResponse)(nil),         // 19: proto.product_service.digital.v1.PublishResponse
	(*ArchiveRequest)(nil),          // 20: proto.product_service.digital.v1.ArchiveRequest
	(*ArchiveResponse)(nil),         // 21: proto.product_service.digital.v1.ArchiveResponse
	(*RestoreRequest)(nil),          // 22: proto.product_service.digital.v1.RestoreRequest
	(*RestoreResponse)(nil),         // 23: proto.product_service.digital.v1.RestoreResponse
	(*PingRequest)(nil),             // 24: proto.product_service.digital.v1.PingRequest
	(*PingResponse)(nil),            // 25: proto.product_service.digital.v1.PingResponse
	(*timestamppb.Timestamp)(nil),   // 26: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),   // 27: google.protobuf.FieldMask
}
var file_proto_product_service_digital_v1_digital_proto_depIdxs = []int32{
	26, // 0: proto.product_service.digital.v1.Asset.created_at:type_name -> google.protobuf.Timestamp
	26, // 1: proto.product_service.digital.v1.Asset.updated_at:type_name -> google.protobuf.Timestamp
	26, // 2: proto.product_service.digital.v1.Asset.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: proto.product_service.digital.v1.Asset.status:type_name -> proto.product_service.digital.v1.AssetStatus
	1,  // 4: proto.product_service.digital.v1.GetResponse.asset:type_name -> proto.product_service.digital.v1.Asset
	1,  // 5: proto.product_service.digital.v1.GetWithDraftResponse.asset:type_name -> proto.product_service.digital.v1.Asset
	1,  // 6: proto.product_service.digital.v1.GetWithArchivedResponse.asset:type_name -> proto.product_service.digital.v1.Asset
	1,  // 7: proto.product_service.digital.v1.ListResponse.assets:type_name -> proto.product_service.digital.v1.Asset
	1,  // 8: proto.product_service.digital.v1.ListDraftsResponse.assets:type_name -> proto.product_service.digital.v1.Asset
	1,  // 9: proto.product_service.digital.v1.ListArchivedResponse.assets:type_name -> proto.product_service.digital.v1.Asset
	1,  // 10: proto.product_service.digital.v1.CreateResponse.asset:type_name -> proto.product_service.digital.v1.Asset
	27, // 11: proto.product_service.digital.v1.UpdateRequest.updates:type_name -> google.protobuf.FieldMask
	27, // 12: proto.product_service.digital.v1.UpdateResponse.updates:type_name -> google.protobuf.FieldMask
	24, // 13: proto.product_service.digital.v1.AssetService.Ping:input_type -> proto.product_service.digital.v1.PingRequest
	2,  // 14: proto.product_service.digital.v1.AssetService.Get:input_type -> proto.product_service.digital.v1.GetRequest
	4,  // 15: proto.product_service.digital.v1.AssetService.GetWithDraft:input_type -> proto.product_service.digital.v1.GetWithDraftRequest
	6,  // 16: proto.product_service.digital.v1.AssetService.GetWithArchived:input_type -> proto.product_service.digital.v1.GetWithArchivedRequest
	8,  // 17: proto.product_service.digital.v1.AssetService.List:input_type -> proto.product_service.digital.v1.ListRequest
	10, // 18: proto.product_service.digital.v1.AssetService.ListDrafts:input_type -> proto.product_service.digital.v1.ListDraftsRequest
	12, // 19: proto.product_service.digital.v1.AssetService.ListArchived:input_type -> proto.product_service.digital.v1.ListArchivedRequest
	14, // 20: proto.product_service.digital.v1.AssetService.Create:input_type -> proto.product_service.digital.v1.CreateRequest
	16, // 21: proto.product_service.digital.v1.AssetService.Update:input_type -> proto.product_service.digital.v1.UpdateRequest
	18, // 22: proto.product_service.digital.v1.AssetService.Publish:input_type -> proto.product_service.digital.v1.PublishRequest
	20, // 23: proto.product_service.digital.v1.AssetService.Archive:input_type -> proto.product_service.digital.v1.ArchiveRequest
	22, // 24: proto.product_service.digital.v1.AssetService.Restore:input_type -> proto.product_service.digital.v1.RestoreRequest
	25, // 25: proto.product_service.digital.v1.AssetService.Ping:output_type -> proto.product_service.digital.v1.PingResponse
	3,  // 26: proto.product_service.digital.v1.AssetService.Get:output_type -> proto.product_service.digital.v1.GetResponse
	5,  // 27: proto.product_service.digital.v1.AssetService.GetWithDraft:output_type -> proto.product_service.digital.v1.GetWithDraftResponse
	7,  // 28: proto.product_service.digital.v1.AssetService.GetWithArchived:output_type -> proto.product_service.digital.v1.GetWithArchivedResponse
	9,  // 29: proto.product_service.digital.v1.AssetService.List:output_type -> proto.product_service.digital.v1.ListResponse
	11, // 30: proto.product_service.digital.v1.AssetService.ListDrafts:output_type -> proto.product_service.digital.v1.ListDraftsResponse
	13, // 31: proto.product_service.digital.v1.AssetService.ListArchived:output_type -> proto.product_service.digital.v1.ListArchivedResponse
	15, // 32: proto.product_service.digital.v1.AssetService.Create:output_type -> proto.product_service.digital.v1.CreateResponse
	17, // 33: proto.product_service.digital.v1.AssetService.Update:output_type -> proto.product_service.digital.v1.UpdateResponse
	19, // 34: proto.product_service.digital.v1.AssetService.Publish:output_type -> proto.product_service.digital.v1.PublishResponse
	21, // 35: proto.product_service.digital.v1.AssetService.Archive:output_type -> proto.product_service.digital.v1.ArchiveResponse
	23, // 36: proto.product_service.digital.v1.AssetService.Restore:output_type -> proto.product_service.digital.v1.RestoreResponse
	25, // [25:37] is the sub-list for method output_type
	13, // [13:25] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_product_service_digital_v1_digital_proto_init() }
func file_proto_product_service_digital_v1_digital_proto_init() {
	if File_proto_product_service_digital_v1_digital_proto != nil {
		return
	}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[15].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[17].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[19].OneofWrappers = []any{}
	file_proto_product_service_digital_v1_digital_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_service_digital_v1_digital_proto_rawDesc), len(file_proto_product_service_digital_v1_digital_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_service_digital_v1_digital_proto_goTypes,
		DependencyIndexes: file_proto_product_service_digital_v1_digital_proto_depIdxs,
		EnumInfos:         file_proto_product_service_digital_v1_digital_proto_enumTypes,
		MessageInfos:      file_proto_product_service_digital_v1_digital_proto_msgTypes,
	}.Build()
	File_proto_product_service_digital_v1_digital_proto = out.File
	file_proto_product_service_digital_v1_digital_proto_goTypes = nil
	file_proto_product_service_digital_v1_digital_proto_depIdxs = nil
}
