// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product_service/image/v1/image.proto

package imagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageStatus int32

const (
	ImageStatus_IMAGE_STATUS_UNSPECIFIED ImageStatus = 0
	ImageStatus_IMAGE_STATUS_ACTIVE      ImageStatus = 1
	ImageStatus_IMAGE_STATUS_DRAFT       ImageStatus = 2
	ImageStatus_IMAGE_STATUS_ARCHIVED    ImageStatus = 3
	ImageStatus_IMAGE_STATUS_BROKEN      ImageStatus = 4
)

// Enum value maps for ImageStatus.
var (
	ImageStatus_name = map[int32]string{
		0: "IMAGE_STATUS_UNSPECIFIED",
		1: "IMAGE_STATUS_ACTIVE",
		2: "IMAGE_STATUS_DRAFT",
		3: "IMAGE_STATUS_ARCHIVED",
		4: "IMAGE_STATUS_BROKEN",
	}
	ImageStatus_value = map[string]int32{
		"IMAGE_STATUS_UNSPECIFIED": 0,
		"IMAGE_STATUS_ACTIVE":      1,
		"IMAGE_STATUS_DRAFT":       2,
		"IMAGE_STATUS_ARCHIVED":    3,
		"IMAGE_STATUS_BROKEN":      4,
	}
)

func (x ImageStatus) Enum() *ImageStatus {
	p := new(ImageStatus)
	*p = x
	return p
}

func (x ImageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_product_service_image_v1_image_proto_enumTypes[0].Descriptor()
}

func (ImageStatus) Type() protoreflect.EnumType {
	return &file_product_service_image_v1_image_proto_enumTypes[0]
}

func (x ImageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageStatus.Descriptor instead.
func (ImageStatus) EnumDescriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{0}
}

type Image struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status           ImageStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=product_service.image.v1.ImageStatus" json:"status,omitempty"`
	MediaServiceUuid []byte                 `protobuf:"bytes,5,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	Url              string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	SecureUrl        string                 `protobuf:"bytes,7,opt,name=secure_url,json=secureUrl,proto3" json:"secure_url,omitempty"`
	PublicId         string                 `protobuf:"bytes,8,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Format           string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"`
	ResourceType     string                 `protobuf:"bytes,10,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Folder           string                 `protobuf:"bytes,11,opt,name=folder,proto3" json:"folder,omitempty"`
	DisplayName      string                 `protobuf:"bytes,12,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Width            *int32                 `protobuf:"varint,13,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height           *int32                 `protobuf:"varint,14,opt,name=height,proto3,oneof" json:"height,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Image) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Image) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Image) GetStatus() ImageStatus {
	if x != nil {
		return x.Status
	}
	return ImageStatus_IMAGE_STATUS_UNSPECIFIED
}

func (x *Image) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetSecureUrl() string {
	if x != nil {
		return x.SecureUrl
	}
	return ""
}

func (x *Image) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *Image) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Image) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Image) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Image) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Image) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type BrokenImageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaServiceUuid []byte                 `protobuf:"bytes,1,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminUuid        []byte                 `protobuf:"bytes,3,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	AdminName        string                 `protobuf:"bytes,4,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BrokenImageRequest) Reset() {
	*x = BrokenImageRequest{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokenImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenImageRequest) ProtoMessage() {}

func (x *BrokenImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenImageRequest.ProtoReflect.Descriptor instead.
func (*BrokenImageRequest) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *BrokenImageRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

func (x *BrokenImageRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BrokenImageRequest) GetAdminUuid() []byte {
	if x != nil {
		return x.AdminUuid
	}
	return nil
}

func (x *BrokenImageRequest) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

type BrokenImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokenImageResponse) Reset() {
	*x = BrokenImageResponse{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokenImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenImageResponse) ProtoMessage() {}

func (x *BrokenImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenImageResponse.ProtoReflect.Descriptor instead.
func (*BrokenImageResponse) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{2}
}

type DeleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaServiceUuid []byte                 `protobuf:"bytes,1,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{4}
}

type ForceDeleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaServiceUuid []byte                 `protobuf:"bytes,1,opt,name=media_service_uuid,json=mediaServiceUuid,proto3" json:"media_service_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForceDeleteRequest) Reset() {
	*x = ForceDeleteRequest{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceDeleteRequest) ProtoMessage() {}

func (x *ForceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ForceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{5}
}

func (x *ForceDeleteRequest) GetMediaServiceUuid() []byte {
	if x != nil {
		return x.MediaServiceUuid
	}
	return nil
}

type ForceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceDeleteResponse) Reset() {
	*x = ForceDeleteResponse{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceDeleteResponse) ProtoMessage() {}

func (x *ForceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ForceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{6}
}

type ForceDeleteBatchRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MediaServiceUuids [][]byte               `protobuf:"bytes,1,rep,name=media_service_uuids,json=mediaServiceUuids,proto3" json:"media_service_uuids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForceDeleteBatchRequest) Reset() {
	*x = ForceDeleteBatchRequest{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceDeleteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceDeleteBatchRequest) ProtoMessage() {}

func (x *ForceDeleteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceDeleteBatchRequest.ProtoReflect.Descriptor instead.
func (*ForceDeleteBatchRequest) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{7}
}

func (x *ForceDeleteBatchRequest) GetMediaServiceUuids() [][]byte {
	if x != nil {
		return x.MediaServiceUuids
	}
	return nil
}

type ForceDeleteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceDeleteBatchResponse) Reset() {
	*x = ForceDeleteBatchResponse{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceDeleteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceDeleteBatchResponse) ProtoMessage() {}

func (x *ForceDeleteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceDeleteBatchResponse.ProtoReflect.Descriptor instead.
func (*ForceDeleteBatchResponse) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{8}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_product_service_image_v1_image_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_service_image_v1_image_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_product_service_image_v1_image_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_product_service_image_v1_image_proto protoreflect.FileDescriptor

const file_product_service_image_v1_image_proto_rawDesc = "" +
	"\n" +
	"$product_service/image/v1/image.proto\x12\x18product_service.image.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x04\n" +
	"\x05Image\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\x06status\x18\x04 \x01(\x0e2%.product_service.image.v1.ImageStatusR\x06status\x12,\n" +
	"\x12media_service_uuid\x18\x05 \x01(\fR\x10mediaServiceUuid\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"secure_url\x18\a \x01(\tR\tsecureUrl\x12\x1b\n" +
	"\tpublic_id\x18\b \x01(\tR\bpublicId\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\x12#\n" +
	"\rresource_type\x18\n" +
	" \x01(\tR\fresourceType\x12\x16\n" +
	"\x06folder\x18\v \x01(\tR\x06folder\x12!\n" +
	"\fdisplay_name\x18\f \x01(\tR\vdisplayName\x12\x19\n" +
	"\x05width\x18\r \x01(\x05H\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x0e \x01(\x05H\x01R\x06height\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_height\"\x98\x01\n" +
	"\x12BrokenImageRequest\x12,\n" +
	"\x12media_service_uuid\x18\x01 \x01(\fR\x10mediaServiceUuid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x03 \x01(\fR\tadminUuid\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x04 \x01(\tR\tadminName\"\x15\n" +
	"\x13BrokenImageResponse\"=\n" +
	"\rDeleteRequest\x12,\n" +
	"\x12media_service_uuid\x18\x01 \x01(\fR\x10mediaServiceUuid\"\x10\n" +
	"\x0eDeleteResponse\"B\n" +
	"\x12ForceDeleteRequest\x12,\n" +
	"\x12media_service_uuid\x18\x01 \x01(\fR\x10mediaServiceUuid\"\x15\n" +
	"\x13ForceDeleteResponse\"I\n" +
	"\x17ForceDeleteBatchRequest\x12.\n" +
	"\x13media_service_uuids\x18\x01 \x03(\fR\x11mediaServiceUuids\"\x1a\n" +
	"\x18ForceDeleteBatchResponse\"\r\n" +
	"\vPingRequest\",\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp*\x90\x01\n" +
	"\vImageStatus\x12\x1c\n" +
	"\x18IMAGE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13IMAGE_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12IMAGE_STATUS_DRAFT\x10\x02\x12\x19\n" +
	"\x15IMAGE_STATUS_ARCHIVED\x10\x03\x12\x17\n" +
	"\x13IMAGE_STATUS_BROKEN\x10\x042\x95\x04\n" +
	"\fImageService\x12U\n" +
	"\x04Ping\x12%.product_service.image.v1.PingRequest\x1a&.product_service.image.v1.PingResponse\x12j\n" +
	"\vBrokenImage\x12,.product_service.image.v1.BrokenImageRequest\x1a-.product_service.image.v1.BrokenImageResponse\x12[\n" +
	"\x06Delete\x12'.product_service.image.v1.DeleteRequest\x1a(.product_service.image.v1.DeleteResponse\x12j\n" +
	"\vForceDelete\x12,.product_service.image.v1.ForceDeleteRequest\x1a-.product_service.image.v1.ForceDeleteResponse\x12y\n" +
	"\x10ForceDeleteBatch\x121.product_service.image.v1.ForceDeleteBatchRequest\x1a2.product_service.image.v1.ForceDeleteBatchResponseB\xfb\x01\n" +
	"\x1ccom.product_service.image.v1B\n" +
	"ImageProtoP\x01ZQgithub.com/mikhail5545/product-service-client/pb/product_service/image/v1;imagev1\xa2\x02\x03PIX\xaa\x02\x17ProductService.Image.V1\xca\x02\x17ProductService\\Image\\V1\xe2\x02#ProductService\\Image\\V1\\GPBMetadata\xea\x02\x19ProductService::Image::V1b\x06proto3"

var (
	file_product_service_image_v1_image_proto_rawDescOnce sync.Once
	file_product_service_image_v1_image_proto_rawDescData []byte
)

func file_product_service_image_v1_image_proto_rawDescGZIP() []byte {
	file_product_service_image_v1_image_proto_rawDescOnce.Do(func() {
		file_product_service_image_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_service_image_v1_image_proto_rawDesc), len(file_product_service_image_v1_image_proto_rawDesc)))
	})
	return file_product_service_image_v1_image_proto_rawDescData
}

var file_product_service_image_v1_image_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_product_service_image_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_service_image_v1_image_proto_goTypes = []any{
	(ImageStatus)(0),                 // 0: product_service.image.v1.ImageStatus
	(*Image)(nil),                    // 1: product_service.image.v1.Image
	(*BrokenImageRequest)(nil),       // 2: product_service.image.v1.BrokenImageRequest
	(*BrokenImageResponse)(nil),      // 3: product_service.image.v1.BrokenImageResponse
	(*DeleteRequest)(nil),            // 4: product_service.image.v1.DeleteRequest
	(*DeleteResponse)(nil),           // 5: product_service.image.v1.DeleteResponse
	(*ForceDeleteRequest)(nil),       // 6: product_service.image.v1.ForceDeleteRequest
	(*ForceDeleteResponse)(nil),      // 7: product_service.image.v1.ForceDeleteResponse
	(*ForceDeleteBatchRequest)(nil),  // 8: product_service.image.v1.ForceDeleteBatchRequest
	(*ForceDeleteBatchResponse)(nil), // 9: product_service.image.v1.ForceDeleteBatchResponse
	(*PingRequest)(nil),              // 10: product_service.image.v1.PingRequest
	(*PingResponse)(nil),             // 11: product_service.image.v1.PingResponse
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_product_service_image_v1_image_proto_depIdxs = []int32{
	12, // 0: product_service.image.v1.Image.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: product_service.image.v1.Image.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: product_service.image.v1.Image.status:type_name -> product_service.image.v1.ImageStatus
	10, // 3: product_service.image.v1.ImageService.Ping:input_type -> product_service.image.v1.PingRequest
	2,  // 4: product_service.image.v1.ImageService.BrokenImage:input_type -> product_service.image.v1.BrokenImageRequest
	4,  // 5: product_service.image.v1.ImageService.Delete:input_type -> product_service.image.v1.DeleteRequest
	6,  // 6: product_service.image.v1.ImageService.ForceDelete:input_type -> product_service.image.v1.ForceDeleteRequest
	8,  // 7: product_service.image.v1.ImageService.ForceDeleteBatch:input_type -> product_service.image.v1.ForceDeleteBatchRequest
	11, // 8: product_service.image.v1.ImageService.Ping:output_type -> product_service.image.v1.PingResponse
	3,  // 9: product_service.image.v1.ImageService.BrokenImage:output_type -> product_service.image.v1.BrokenImageResponse
	5,  // 10: product_service.image.v1.ImageService.Delete:output_type -> product_service.image.v1.DeleteResponse
	7,  // 11: product_service.image.v1.ImageService.ForceDelete:output_type -> product_service.image.v1.ForceDeleteResponse
	9,  // 12: product_service.image.v1.ImageService.ForceDeleteBatch:output_type -> product_service.image.v1.ForceDeleteBatchResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_product_service_image_v1_image_proto_init() }
func file_product_service_image_v1_image_proto_init() {
	if File_product_service_image_v1_image_proto != nil {
		return
	}
	file_product_service_image_v1_image_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_service_image_v1_image_proto_rawDesc), len(file_product_service_image_v1_image_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_service_image_v1_image_proto_goTypes,
		DependencyIndexes: file_product_service_image_v1_image_proto_depIdxs,
		EnumInfos:         file_product_service_image_v1_image_proto_enumTypes,
		MessageInfos:      file_product_service_image_v1_image_proto_msgTypes,
	}.Build()
	File_product_service_image_v1_image_proto = out.File
	file_product_service_image_v1_image_proto_goTypes = nil
	file_product_service_image_v1_image_proto_depIdxs = nil
}
